"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class Accountnames(object):
    """Implementation of the 'accountnames' model.

    Attributes:
        account_name_list (List[str]): The model property of type List[str].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_name_list": "accountNameList",
    }

    _optionals = [
        "account_name_list",
    ]

    def __init__(
        self,
        account_name_list=APIHelper.SKIP):
        """Initialize a Accountnames instance."""
        # Initialize members of the class
        if account_name_list is not APIHelper.SKIP:
            self.account_name_list = account_name_list

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_name_list =\
            dictionary.get("accountNameList")\
            if dictionary.get("accountNameList")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_name_list)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_name_list=(
            self.account_name_list
            if hasattr(self, "account_name_list")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_name_list={_account_name_list!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_name_list=(
            self.account_name_list
            if hasattr(self, "account_name_list")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_name_list={_account_name_list!s}, "
            f")"
        )
