"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.account_share_filter_criteria import (
    AccountShareFilterCriteria,
)
from verizon.models.change_plan_details import (
    ChangePlanDetails,
)


class AccountSharePricePlanTrigger(object):
    """Implementation of the 'accountSharePricePlanTrigger' model.

    Attributes:
        account_share (AccountShareFilterCriteria): The model property of type
            AccountShareFilterCriteria.
        condition (ConditionTypeEnum | ConditionObjectCall | None): The model
            property of type ConditionTypeEnum | ConditionObjectCall | None.
        change_plan (bool): a flag to set if the trigger changes service plans, true,
            or not, false
        change_plan_details (ChangePlanDetails): The service plan code to switch to

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_share": "accountShare",
        "condition": "condition",
        "change_plan": "changePlan",
        "change_plan_details": "changePlanDetails",
    }

    _optionals = [
        "account_share",
        "condition",
        "change_plan",
        "change_plan_details",
    ]

    def __init__(
        self,
        account_share=APIHelper.SKIP,
        condition=APIHelper.SKIP,
        change_plan=APIHelper.SKIP,
        change_plan_details=APIHelper.SKIP):
        """Initialize a AccountSharePricePlanTrigger instance."""
        # Initialize members of the class
        if account_share is not APIHelper.SKIP:
            self.account_share = account_share
        if condition is not APIHelper.SKIP:
            self.condition = condition
        if change_plan is not APIHelper.SKIP:
            self.change_plan = change_plan
        if change_plan_details is not APIHelper.SKIP:
            self.change_plan_details = change_plan_details

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_share =\
            AccountShareFilterCriteria.from_dictionary(
                dictionary.get("accountShare"))\
                if "accountShare" in dictionary.keys()\
                else APIHelper.SKIP
        condition = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("AccountSharePricePlanTriggerCondition"),
            dictionary.get("condition"),
            False)\
            if dictionary.get("condition") is not None\
            else APIHelper.SKIP
        change_plan =\
            dictionary.get("changePlan")\
            if "changePlan" in dictionary.keys()\
                else APIHelper.SKIP
        change_plan_details =\
            ChangePlanDetails.from_dictionary(
                dictionary.get("changePlanDetails"))\
                if "changePlanDetails" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_share,
                   condition,
                   change_plan,
                   change_plan_details)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_share=(
            self.account_share
            if hasattr(self, "account_share")
            else None
        )
        _condition=(
            self.condition
            if hasattr(self, "condition")
            else None
        )
        _change_plan=(
            self.change_plan
            if hasattr(self, "change_plan")
            else None
        )
        _change_plan_details=(
            self.change_plan_details
            if hasattr(self, "change_plan_details")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_share={_account_share!r}, "
            f"condition={_condition!r}, "
            f"change_plan={_change_plan!r}, "
            f"change_plan_details={_change_plan_details!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_share=(
            self.account_share
            if hasattr(self, "account_share")
            else None
        )
        _condition=(
            self.condition
            if hasattr(self, "condition")
            else None
        )
        _change_plan=(
            self.change_plan
            if hasattr(self, "change_plan")
            else None
        )
        _change_plan_details=(
            self.change_plan_details
            if hasattr(self, "change_plan_details")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_share={_account_share!s}, "
            f"condition={_condition!s}, "
            f"change_plan={_change_plan!s}, "
            f"change_plan_details={_change_plan_details!s}, "
            f")"
        )
