"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.account_group_share_filter_criteria import (
    AccountGroupShareFilterCriteria,
)


class AccountGroupShareIndividual1(object):
    """Implementation of the 'accountGroupShareIndividual1' model.

    Attributes:
        account_group_share_individual (AccountGroupShareFilterCriteria): The model
            property of type AccountGroupShareFilterCriteria.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_group_share_individual": "accountGroupShareIndividual",
    }

    _optionals = [
        "account_group_share_individual",
    ]

    def __init__(
        self,
        account_group_share_individual=APIHelper.SKIP):
        """Initialize a AccountGroupShareIndividual1 instance."""
        # Initialize members of the class
        if account_group_share_individual is not APIHelper.SKIP:
            self.account_group_share_individual = account_group_share_individual

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_group_share_individual =\
            AccountGroupShareFilterCriteria.from_dictionary(
                dictionary.get("accountGroupShareIndividual"))\
                if "accountGroupShareIndividual" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_group_share_individual)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_group_share_individual=(
            self.account_group_share_individual
            if hasattr(self, "account_group_share_individual")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_group_share_individual={_account_group_share_individual!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_group_share_individual=(
            self.account_group_share_individual
            if hasattr(self, "account_group_share_individual")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_group_share_individual={_account_group_share_individual!s}, "
            f")"
        )
