"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class AccountGroupShareCondition(object):
    """Implementation of the 'accountGroupShareCondition' model.

    Attributes:
        action (ConditionActionEnum): The action taken when trigger conditions are met

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "action": "action",
    }

    _optionals = [
        "action",
    ]

    def __init__(
        self,
        action=APIHelper.SKIP):
        """Initialize a AccountGroupShareCondition instance."""
        # Initialize members of the class
        if action is not APIHelper.SKIP:
            self.action = action

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        action =\
            dictionary.get("action")\
            if dictionary.get("action")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(action)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _action=(
            self.action
            if hasattr(self, "action")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"action={_action!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _action=(
            self.action
            if hasattr(self, "action")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"action={_action!s}, "
            f")"
        )
