"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.data_trigger import DataTrigger
from verizon.models.notificationarray import (
    Notificationarray,
)


class AccountLevelCreateTrigger(object):
    """Implementation of the 'accountLevelCreateTrigger' model.

    Attributes:
        trigger_name (str): The user defined name of the trigger
        ecpd_id (str): The Enterprise Customer Profile Database ID
        trigger_category (TriggerCategoryEnum): The type of trigger being created or
            modified
        data_trigger (DataTrigger): The model property of type DataTrigger.
        notification (Notificationarray): The model property of type
            Notificationarray.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "trigger_name": "triggerName",
        "ecpd_id": "ecpdId",
        "trigger_category": "triggerCategory",
        "data_trigger": "dataTrigger",
        "notification": "notification",
    }

    _optionals = [
        "trigger_name",
        "ecpd_id",
        "trigger_category",
        "data_trigger",
        "notification",
    ]

    def __init__(
        self,
        trigger_name=APIHelper.SKIP,
        ecpd_id=APIHelper.SKIP,
        trigger_category=APIHelper.SKIP,
        data_trigger=APIHelper.SKIP,
        notification=APIHelper.SKIP):
        """Initialize a AccountLevelCreateTrigger instance."""
        # Initialize members of the class
        if trigger_name is not APIHelper.SKIP:
            self.trigger_name = trigger_name
        if ecpd_id is not APIHelper.SKIP:
            self.ecpd_id = ecpd_id
        if trigger_category is not APIHelper.SKIP:
            self.trigger_category = trigger_category
        if data_trigger is not APIHelper.SKIP:
            self.data_trigger = data_trigger
        if notification is not APIHelper.SKIP:
            self.notification = notification

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        trigger_name =\
            dictionary.get("triggerName")\
            if dictionary.get("triggerName")\
                else APIHelper.SKIP
        ecpd_id =\
            dictionary.get("ecpdId")\
            if dictionary.get("ecpdId")\
                else APIHelper.SKIP
        trigger_category =\
            dictionary.get("triggerCategory")\
            if dictionary.get("triggerCategory")\
                else APIHelper.SKIP
        data_trigger =\
            DataTrigger.from_dictionary(
                dictionary.get("dataTrigger"))\
                if "dataTrigger" in dictionary.keys()\
                else APIHelper.SKIP
        notification =\
            Notificationarray.from_dictionary(
                dictionary.get("notification"))\
                if "notification" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(trigger_name,
                   ecpd_id,
                   trigger_category,
                   data_trigger,
                   notification)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _trigger_name=(
            self.trigger_name
            if hasattr(self, "trigger_name")
            else None
        )
        _ecpd_id=(
            self.ecpd_id
            if hasattr(self, "ecpd_id")
            else None
        )
        _trigger_category=(
            self.trigger_category
            if hasattr(self, "trigger_category")
            else None
        )
        _data_trigger=(
            self.data_trigger
            if hasattr(self, "data_trigger")
            else None
        )
        _notification=(
            self.notification
            if hasattr(self, "notification")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"trigger_name={_trigger_name!r}, "
            f"ecpd_id={_ecpd_id!r}, "
            f"trigger_category={_trigger_category!r}, "
            f"data_trigger={_data_trigger!r}, "
            f"notification={_notification!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _trigger_name=(
            self.trigger_name
            if hasattr(self, "trigger_name")
            else None
        )
        _ecpd_id=(
            self.ecpd_id
            if hasattr(self, "ecpd_id")
            else None
        )
        _trigger_category=(
            self.trigger_category
            if hasattr(self, "trigger_category")
            else None
        )
        _data_trigger=(
            self.data_trigger
            if hasattr(self, "data_trigger")
            else None
        )
        _notification=(
            self.notification
            if hasattr(self, "notification")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"trigger_name={_trigger_name!s}, "
            f"ecpd_id={_ecpd_id!s}, "
            f"trigger_category={_trigger_category!s}, "
            f"data_trigger={_data_trigger!s}, "
            f"notification={_notification!s}, "
            f")"
        )
