"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.address import Address


class Addressquery(object):
    """Implementation of the 'addressquery' model.

    Attributes:
        address (List[Address]): The model property of type List[Address].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address": "address",
    }

    _optionals = [
        "address",
    ]

    def __init__(
        self,
        address=APIHelper.SKIP):
        """Initialize a Addressquery instance."""
        # Initialize members of the class
        if address is not APIHelper.SKIP:
            self.address = address

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address = None
        if dictionary.get("address") is not None:
            address = [
                Address.from_dictionary(x)
                    for x in dictionary.get("address")
            ]
        else:
            address = APIHelper.SKIP

        # Return an object of this model
        return cls(address)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"address={_address!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"address={_address!s}, "
            f")"
        )
