"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class AggregateSessionReportRequest(object):
    """Implementation of the 'AggregateSessionReportRequest' model.

    Request for getting an aggregated session report.

    Attributes:
        account_number (str): The numeric ID of the account and must include leading
            zeroes. This value is indentical to `accountName`.
        start_date (str): Start date of session to include. If not specified
            information will be shown from the earliest available (180 days). Can be
            either date in ISO 8601 format or predefined constants.
        end_date (str): End date of session to include. If not specified  information
            will be shown to the latest available. Can be either date in ISO 8601
            format or predefined constants.
        imei (List[str]): Devices for which return usage info. Could be 0, 1 or more.
            In case of 0 will return all devices belonging to customer (except of
            filtered by other parameters).
        device_group (str): Optional filter — only include devices matching this
            device group name.
        data_plan (str): Optional filter — only include devices matching this carrier
            rate plan code.
        no_session_flag (bool): Optional filter — when "true", returns only devices
            with no sessions.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_number": "accountNumber",
        "imei": "imei",
        "start_date": "startDate",
        "end_date": "endDate",
        "device_group": "deviceGroup",
        "data_plan": "dataPlan",
        "no_session_flag": "noSessionFlag",
    }

    _optionals = [
        "start_date",
        "end_date",
        "device_group",
        "data_plan",
        "no_session_flag",
    ]

    def __init__(
        self,
        account_number=None,
        imei=None,
        start_date=APIHelper.SKIP,
        end_date=APIHelper.SKIP,
        device_group=APIHelper.SKIP,
        data_plan=APIHelper.SKIP,
        no_session_flag=APIHelper.SKIP):
        """Initialize a AggregateSessionReportRequest instance."""
        # Initialize members of the class
        self.account_number = account_number
        if start_date is not APIHelper.SKIP:
            self.start_date = start_date
        if end_date is not APIHelper.SKIP:
            self.end_date = end_date
        self.imei = imei
        if device_group is not APIHelper.SKIP:
            self.device_group = device_group
        if data_plan is not APIHelper.SKIP:
            self.data_plan = data_plan
        if no_session_flag is not APIHelper.SKIP:
            self.no_session_flag = no_session_flag

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_number =\
            dictionary.get("accountNumber")\
            if dictionary.get("accountNumber")\
                else None
        imei =\
            dictionary.get("imei")\
            if dictionary.get("imei")\
                else None
        start_date =\
            dictionary.get("startDate")\
            if dictionary.get("startDate")\
                else APIHelper.SKIP
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else APIHelper.SKIP
        device_group =\
            dictionary.get("deviceGroup")\
            if dictionary.get("deviceGroup")\
                else APIHelper.SKIP
        data_plan =\
            dictionary.get("dataPlan")\
            if dictionary.get("dataPlan")\
                else APIHelper.SKIP
        no_session_flag =\
            dictionary.get("noSessionFlag")\
            if "noSessionFlag" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_number,
                   imei,
                   start_date,
                   end_date,
                   device_group,
                   data_plan,
                   no_session_flag)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_number=self.account_number
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _imei=self.imei
        _device_group=(
            self.device_group
            if hasattr(self, "device_group")
            else None
        )
        _data_plan=(
            self.data_plan
            if hasattr(self, "data_plan")
            else None
        )
        _no_session_flag=(
            self.no_session_flag
            if hasattr(self, "no_session_flag")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!r}, "
            f"start_date={_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"imei={_imei!r}, "
            f"device_group={_device_group!r}, "
            f"data_plan={_data_plan!r}, "
            f"no_session_flag={_no_session_flag!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_number=self.account_number
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _imei=self.imei
        _device_group=(
            self.device_group
            if hasattr(self, "device_group")
            else None
        )
        _data_plan=(
            self.data_plan
            if hasattr(self, "data_plan")
            else None
        )
        _no_session_flag=(
            self.no_session_flag
            if hasattr(self, "no_session_flag")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!s}, "
            f"start_date={_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"imei={_imei!s}, "
            f"device_group={_device_group!s}, "
            f"data_plan={_data_plan!s}, "
            f"no_session_flag={_no_session_flag!s}, "
            f")"
        )
