"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AwarenessDistanceEnum(object):
    """Implementation of the 'AwarenessDistance' enum.

    Specifies how far the event is relevant to.

    Attributes:
        LESSTHAN50M: The enum member of type str.
        LESSTHAN100M: The enum member of type str.
        LESSTHAN200M: The enum member of type str.
        LESSTHAN500M: The enum member of type str.
        LESSTHAN1000M: The enum member of type str.
        LESSTHAN5KM: The enum member of type str.
        LESSTHAN10KM: The enum member of type str.
        OVER10KM: The enum member of type str.

    """

    _all_values = ["lessThan50m", "lessThan100m", "lessThan200m", "lessThan500m", "lessThan1000m",
        "lessThan5km", "lessThan10km", "over10km"]
    LESSTHAN50M = "lessThan50m"

    LESSTHAN100M = "lessThan100m"

    LESSTHAN200M = "lessThan200m"

    LESSTHAN500M = "lessThan500m"

    LESSTHAN1000M = "lessThan1000m"

    LESSTHAN5KM = "lessThan5km"

    LESSTHAN10KM = "lessThan10km"

    OVER10KM = "over10km"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
