"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.allowance_threshold import (
    AllowanceThreshold,
)


class Carriercode1(object):
    """Implementation of the 'carriercode1' model.

    Attributes:
        carrier_code (str): The model property of type str.
        percentage (AllowanceThreshold): The model property of type
            AllowanceThreshold.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "carrier_code": "carrierCode",
        "percentage": "percentage",
    }

    _optionals = [
        "carrier_code",
        "percentage",
    ]

    def __init__(
        self,
        carrier_code=APIHelper.SKIP,
        percentage=APIHelper.SKIP):
        """Initialize a Carriercode1 instance."""
        # Initialize members of the class
        if carrier_code is not APIHelper.SKIP:
            self.carrier_code = carrier_code
        if percentage is not APIHelper.SKIP:
            self.percentage = percentage

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        carrier_code =\
            dictionary.get("carrierCode")\
            if dictionary.get("carrierCode")\
                else APIHelper.SKIP
        percentage =\
            AllowanceThreshold.from_dictionary(
                dictionary.get("percentage"))\
                if "percentage" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(carrier_code,
                   percentage)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _carrier_code=(
            self.carrier_code
            if hasattr(self, "carrier_code")
            else None
        )
        _percentage=(
            self.percentage
            if hasattr(self, "percentage")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"carrier_code={_carrier_code!r}, "
            f"percentage={_percentage!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _carrier_code=(
            self.carrier_code
            if hasattr(self, "carrier_code")
            else None
        )
        _percentage=(
            self.percentage
            if hasattr(self, "percentage")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"carrier_code={_carrier_code!s}, "
            f"percentage={_percentage!s}, "
            f")"
        )
