"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class ChangePlanDetails(object):
    """Implementation of the 'changePlanDetails' model.

    The service plan code to switch to

    Attributes:
        to_carrier_service_plan_code (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "to_carrier_service_plan_code": "toCarrierServicePlanCode",
    }

    _optionals = [
        "to_carrier_service_plan_code",
    ]

    def __init__(
        self,
        to_carrier_service_plan_code=APIHelper.SKIP):
        """Initialize a ChangePlanDetails instance."""
        # Initialize members of the class
        if to_carrier_service_plan_code is not APIHelper.SKIP:
            self.to_carrier_service_plan_code = to_carrier_service_plan_code

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        to_carrier_service_plan_code =\
            dictionary.get("toCarrierServicePlanCode")\
            if dictionary.get("toCarrierServicePlanCode")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(to_carrier_service_plan_code)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _to_carrier_service_plan_code=(
            self.to_carrier_service_plan_code
            if hasattr(self, "to_carrier_service_plan_code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"to_carrier_service_plan_code={_to_carrier_service_plan_code!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _to_carrier_service_plan_code=(
            self.to_carrier_service_plan_code
            if hasattr(self, "to_carrier_service_plan_code")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"to_carrier_service_plan_code={_to_carrier_service_plan_code!s}, "
            f")"
        )
