"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class ConnectionResponse(object):
    """Implementation of the 'ConnectionResponse' model.

    response for /clients/connection

    Attributes:
        mqtt_url (str): The full MQTT URL including protocol, host, and port.
        host (str): The hostname of the MQTT broker to connect to.
        port (int): The port number of the MQTT broker.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mqtt_url": "MqttURL",
        "host": "Host",
        "port": "Port",
    }

    _optionals = [
        "host",
        "port",
    ]

    def __init__(
        self,
        mqtt_url=None,
        host=APIHelper.SKIP,
        port=APIHelper.SKIP):
        """Initialize a ConnectionResponse instance."""
        # Initialize members of the class
        self.mqtt_url = mqtt_url
        if host is not APIHelper.SKIP:
            self.host = host
        if port is not APIHelper.SKIP:
            self.port = port

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mqtt_url =\
            dictionary.get("MqttURL")\
            if dictionary.get("MqttURL")\
                else None
        host =\
            dictionary.get("Host")\
            if dictionary.get("Host")\
                else APIHelper.SKIP
        port =\
            dictionary.get("Port")\
            if dictionary.get("Port")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(mqtt_url,
                   host,
                   port)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mqtt_url=self.mqtt_url
        _host=(
            self.host
            if hasattr(self, "host")
            else None
        )
        _port=(
            self.port
            if hasattr(self, "port")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mqtt_url={_mqtt_url!r}, "
            f"host={_host!r}, "
            f"port={_port!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mqtt_url=self.mqtt_url
        _host=(
            self.host
            if hasattr(self, "host")
            else None
        )
        _port=(
            self.port
            if hasattr(self, "port")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"mqtt_url={_mqtt_url!s}, "
            f"host={_host!s}, "
            f"port={_port!s}, "
            f")"
        )
