"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.gio_device_id import GIODeviceId


class DailyUsage(object):
    """Implementation of the 'dailyUsage' model.

    Attributes:
        device_id (GIODeviceId): The model property of type GIODeviceId.
        earliest (str): The start date of the time period queried as "$datetime"
        latest (str): The end date of the time period being queried as "$datetime"

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_id": "deviceId",
        "earliest": "earliest",
        "latest": "latest",
    }

    _optionals = [
        "device_id",
        "earliest",
        "latest",
    ]

    def __init__(
        self,
        device_id=APIHelper.SKIP,
        earliest=APIHelper.SKIP,
        latest=APIHelper.SKIP):
        """Initialize a DailyUsage instance."""
        # Initialize members of the class
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id
        if earliest is not APIHelper.SKIP:
            self.earliest = earliest
        if latest is not APIHelper.SKIP:
            self.latest = latest

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        device_id =\
            GIODeviceId.from_dictionary(
                dictionary.get("deviceId"))\
                if "deviceId" in dictionary.keys()\
                else APIHelper.SKIP
        earliest =\
            dictionary.get("earliest")\
            if dictionary.get("earliest")\
                else APIHelper.SKIP
        latest =\
            dictionary.get("latest")\
            if dictionary.get("latest")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(device_id,
                   earliest,
                   latest)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _earliest=(
            self.earliest
            if hasattr(self, "earliest")
            else None
        )
        _latest=(
            self.latest
            if hasattr(self, "latest")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"device_id={_device_id!r}, "
            f"earliest={_earliest!r}, "
            f"latest={_latest!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _earliest=(
            self.earliest
            if hasattr(self, "earliest")
            else None
        )
        _latest=(
            self.latest
            if hasattr(self, "latest")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"device_id={_device_id!s}, "
            f"earliest={_earliest!s}, "
            f"latest={_latest!s}, "
            f")"
        )
