"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.frame_type_enum import FrameTypeEnum
from verizon.models.geographical_path import (
    GeographicalPath,
)


class DataFrame(object):
    """Implementation of the 'DataFrame' model.

    The data frame allows sending various advisory and road sign types of information
    to equipped devices.

    Attributes:
        do_not_use_1 (int): Always set to 0 and carries no meaning. Legacy field
            maintained for backward compatibility.
        frame_type (FrameTypeEnum): The frameType data element provides the type of
            message to follow in the rest of the message frame structure. The
            following frame types are supported:  - unknown  - advisory  -
            roadSignage  - commercialSignage
        msg_id (FurtherInfoMsgId | RoadSignMsgId): The model property of type
            FurtherInfoMsgId | RoadSignMsgId.
        start_year (int): The V2X year consists of integer values from zero to 4095
            representing the year according to the Gregorian calendar date system.
            The value of zero shall represent an unknown value.
        start_time (int): Start time expresses the number of elapsed minutes of the
            current year in the time system being used (typically UTC time). The
            value 527040 shall be used for invalid.
        duration_time (int): The duration, in units of whole minutes, that a object
            persists for. A value of 32000 means that the object persists forever.
            The range 0..32000 provides for about 22.2 days of maximum duration.
        priority (int): The relative importance of the sign, on a scale from zero
            (least important) to seven (most important).
        do_not_use_2 (int): Always set to 0 and carries no meaning. Legacy field
            maintained for backward compatibility.
        regions (List[GeographicalPath]): The data frame is used to support the
            cross-cutting need in many V2X messages to describe arbitrary spatial
            areas (polygons, boundary lines, and other basic shapes) required by
            various message types in a small message size. This data frame can
            describe a complex path or region of arbitrary size using either one of
            the two supported node offset methods (XY offsets or LL offsets) or using
            simple geometric projections.
        do_not_use_3 (int): Always set to 0 and carries no meaning. Legacy field
            maintained for backward compatibility.
        do_not_use_4 (int): Always set to 0 and carries no meaning. Legacy field
            maintained for backward compatibility.
        content (AdvisoryContent | WorkZoneContent | GenericSignContent |
            SpeedLimitContent | ExitServiceContent): The model property of type
            AdvisoryContent | WorkZoneContent | GenericSignContent |
            SpeedLimitContent | ExitServiceContent.
        content_new (ContentFrictionInfo | None): It contains information that
            extends the original traveler data frame to enable addition of future
            entities. Friction information is the first entity included in the new
            part three content.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "frame_type": "frameType",
        "msg_id": "msgId",
        "start_time": "startTime",
        "duration_time": "durationTime",
        "priority": "priority",
        "regions": "regions",
        "content": "content",
        "do_not_use_1": "doNotUse1",
        "start_year": "startYear",
        "do_not_use_2": "doNotUse2",
        "do_not_use_3": "doNotUse3",
        "do_not_use_4": "doNotUse4",
        "content_new": "contentNew",
    }

    _optionals = [
        "do_not_use_1",
        "start_year",
        "do_not_use_2",
        "do_not_use_3",
        "do_not_use_4",
        "content_new",
    ]

    def __init__(
        self,
        frame_type=None,
        msg_id=None,
        start_time=None,
        duration_time=None,
        priority=None,
        regions=None,
        content=None,
        do_not_use_1=0,
        start_year=APIHelper.SKIP,
        do_not_use_2=0,
        do_not_use_3=0,
        do_not_use_4=0,
        content_new=APIHelper.SKIP):
        """Initialize a DataFrame instance."""
        # Initialize members of the class
        self.do_not_use_1 = do_not_use_1
        self.frame_type = frame_type
        self.msg_id = msg_id
        if start_year is not APIHelper.SKIP:
            self.start_year = start_year
        self.start_time = start_time
        self.duration_time = duration_time
        self.priority = priority
        self.do_not_use_2 = do_not_use_2
        self.regions = regions
        self.do_not_use_3 = do_not_use_3
        self.do_not_use_4 = do_not_use_4
        self.content = content
        if content_new is not APIHelper.SKIP:
            self.content_new = content_new

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        frame_type =\
            dictionary.get("frameType")\
            if dictionary.get("frameType")\
                else None
        msg_id = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DataFrameMsgId"),
            dictionary.get("msgId"),
            False)\
            if dictionary.get("msgId") is not None\
            else None
        start_time =\
            dictionary.get("startTime")\
            if dictionary.get("startTime")\
                else None
        duration_time =\
            dictionary.get("durationTime")\
            if dictionary.get("durationTime")\
                else None
        priority =\
            dictionary.get("priority")\
            if dictionary.get("priority")\
                else None
        regions = None
        if dictionary.get("regions") is not None:
            regions = [
                GeographicalPath.from_dictionary(x)
                    for x in dictionary.get("regions")
            ]
        content = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DataFrameContent"),
            dictionary.get("content"),
            False)\
            if dictionary.get("content") is not None\
            else None
        do_not_use_1 =\
            dictionary.get("doNotUse1")\
            if dictionary.get("doNotUse1")\
                else 0
        start_year =\
            dictionary.get("startYear")\
            if dictionary.get("startYear")\
                else APIHelper.SKIP
        do_not_use_2 =\
            dictionary.get("doNotUse2")\
            if dictionary.get("doNotUse2")\
                else 0
        do_not_use_3 =\
            dictionary.get("doNotUse3")\
            if dictionary.get("doNotUse3")\
                else 0
        do_not_use_4 =\
            dictionary.get("doNotUse4")\
            if dictionary.get("doNotUse4")\
                else 0
        content_new = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DataFrameContentNew"),
            dictionary.get("contentNew"),
            False)\
            if dictionary.get("contentNew") is not None\
            else APIHelper.SKIP

        # Return an object of this model
        return cls(frame_type,
                   msg_id,
                   start_time,
                   duration_time,
                   priority,
                   regions,
                   content,
                   do_not_use_1,
                   start_year,
                   do_not_use_2,
                   do_not_use_3,
                   do_not_use_4,
                   content_new)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.frame_type,
                    type_callable=lambda value:
                        FrameTypeEnum.validate(value)) \
                and (UnionTypeLookUp.get("DataFrameMsgId")
                .validate(dictionary.msg_id).is_valid) \
                and APIHelper.is_valid_type(
                    value=dictionary.start_time,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.duration_time,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.priority,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.regions,
                    type_callable=lambda value:
                        GeographicalPath.validate(value),
                    is_model_dict=True,
                    is_inner_model_dict=True) \
                and (UnionTypeLookUp.get("DataFrameContent")
                .validate(dictionary.content).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("frameType"),
                type_callable=lambda value:
                    FrameTypeEnum.validate(value)) \
            and (UnionTypeLookUp.get("DataFrameMsgId")
            .validate(dictionary.get("msgId")).is_valid) \
            and APIHelper.is_valid_type(
                value=dictionary.get("startTime"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("durationTime"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("priority"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("regions"),
                type_callable=lambda value:
                    GeographicalPath.validate(value),
                is_model_dict=True,
                is_inner_model_dict=True) \
            and (UnionTypeLookUp.get("DataFrameContent")
            .validate(dictionary.get("content")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _do_not_use_1=(
            self.do_not_use_1
            if hasattr(self, "do_not_use_1")
            else None
        )
        _frame_type=self.frame_type
        _msg_id=self.msg_id
        _start_year=(
            self.start_year
            if hasattr(self, "start_year")
            else None
        )
        _start_time=self.start_time
        _duration_time=self.duration_time
        _priority=self.priority
        _do_not_use_2=(
            self.do_not_use_2
            if hasattr(self, "do_not_use_2")
            else None
        )
        _regions=self.regions
        _do_not_use_3=(
            self.do_not_use_3
            if hasattr(self, "do_not_use_3")
            else None
        )
        _do_not_use_4=(
            self.do_not_use_4
            if hasattr(self, "do_not_use_4")
            else None
        )
        _content=self.content
        _content_new=(
            self.content_new
            if hasattr(self, "content_new")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"do_not_use_1={_do_not_use_1!r}, "
            f"frame_type={_frame_type!r}, "
            f"msg_id={_msg_id!r}, "
            f"start_year={_start_year!r}, "
            f"start_time={_start_time!r}, "
            f"duration_time={_duration_time!r}, "
            f"priority={_priority!r}, "
            f"do_not_use_2={_do_not_use_2!r}, "
            f"regions={_regions!r}, "
            f"do_not_use_3={_do_not_use_3!r}, "
            f"do_not_use_4={_do_not_use_4!r}, "
            f"content={_content!r}, "
            f"content_new={_content_new!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _do_not_use_1=(
            self.do_not_use_1
            if hasattr(self, "do_not_use_1")
            else None
        )
        _frame_type=self.frame_type
        _msg_id=self.msg_id
        _start_year=(
            self.start_year
            if hasattr(self, "start_year")
            else None
        )
        _start_time=self.start_time
        _duration_time=self.duration_time
        _priority=self.priority
        _do_not_use_2=(
            self.do_not_use_2
            if hasattr(self, "do_not_use_2")
            else None
        )
        _regions=self.regions
        _do_not_use_3=(
            self.do_not_use_3
            if hasattr(self, "do_not_use_3")
            else None
        )
        _do_not_use_4=(
            self.do_not_use_4
            if hasattr(self, "do_not_use_4")
            else None
        )
        _content=self.content
        _content_new=(
            self.content_new
            if hasattr(self, "content_new")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"do_not_use_1={_do_not_use_1!s}, "
            f"frame_type={_frame_type!s}, "
            f"msg_id={_msg_id!s}, "
            f"start_year={_start_year!s}, "
            f"start_time={_start_time!s}, "
            f"duration_time={_duration_time!s}, "
            f"priority={_priority!s}, "
            f"do_not_use_2={_do_not_use_2!s}, "
            f"regions={_regions!s}, "
            f"do_not_use_3={_do_not_use_3!s}, "
            f"do_not_use_4={_do_not_use_4!s}, "
            f"content={_content!s}, "
            f"content_new={_content_new!s}, "
            f")"
        )
