"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.account_group_share_individual_1 import (
    AccountGroupShareIndividual1,
)
from verizon.models.account_level_filter import (
    AccountLevelFilter,
)
from verizon.models.allowance_threshold import (
    AllowanceThreshold,
)
from verizon.models.device_group_filter_criteria import (
    DeviceGroupFilterCriteria,
)


class DataTrigger5(object):
    """Implementation of the 'DataTrigger5' model.

    Attributes:
        filter_criteria (AccountLevelFilter): The model property of type
            AccountLevelFilter.
        condition (ConditionTypeEnum | ConditionObjectCall | None): The model
            property of type ConditionTypeEnum | ConditionObjectCall | None.
        action (AccountLevelActionEnum): The action taken when trigger conditions are
            met
        condition_type (ConditionTypeEnum): The condition type being monitored
        comparitor (ComparitorEnum): The boolean of the comparison. `gt` is Greater
            Than, `lt` is Less Than and `eq` is Equal To
        threshold (int): The threshold value the trigger monitors for
        threshold_unit (ThresholdUnitEnum): The units of the threshold. This can be
            KB, Kilobits, MB, Megabits, or GB, Gigabits
        cycle_type (RulesCycleTypeEnum): The interval to monitor for the threshold.
            This can be Daily, Weekly or Monthly
        allowance_threshold (AllowanceThreshold): The model property of type
            AllowanceThreshold.
        device_group (DeviceGroupFilterCriteria): The model property of type
            DeviceGroupFilterCriteria.
        account_group_share (AccountGroupShareIndividual1): The model property of
            type AccountGroupShareIndividual1.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "filter_criteria": "filterCriteria",
        "condition": "condition",
        "action": "action",
        "condition_type": "conditionType",
        "comparitor": "comparitor",
        "threshold": "threshold",
        "threshold_unit": "thresholdUnit",
        "cycle_type": "cycleType",
        "allowance_threshold": "allowanceThreshold",
        "device_group": "deviceGroup",
        "account_group_share": "accountGroupShare",
    }

    _optionals = [
        "filter_criteria",
        "condition",
        "action",
        "condition_type",
        "comparitor",
        "threshold",
        "threshold_unit",
        "cycle_type",
        "allowance_threshold",
        "device_group",
        "account_group_share",
    ]

    def __init__(
        self,
        filter_criteria=APIHelper.SKIP,
        condition=APIHelper.SKIP,
        action=APIHelper.SKIP,
        condition_type=APIHelper.SKIP,
        comparitor=APIHelper.SKIP,
        threshold=APIHelper.SKIP,
        threshold_unit=APIHelper.SKIP,
        cycle_type=APIHelper.SKIP,
        allowance_threshold=APIHelper.SKIP,
        device_group=APIHelper.SKIP,
        account_group_share=APIHelper.SKIP):
        """Initialize a DataTrigger5 instance."""
        # Initialize members of the class
        if filter_criteria is not APIHelper.SKIP:
            self.filter_criteria = filter_criteria
        if condition is not APIHelper.SKIP:
            self.condition = condition
        if action is not APIHelper.SKIP:
            self.action = action
        if condition_type is not APIHelper.SKIP:
            self.condition_type = condition_type
        if comparitor is not APIHelper.SKIP:
            self.comparitor = comparitor
        if threshold is not APIHelper.SKIP:
            self.threshold = threshold
        if threshold_unit is not APIHelper.SKIP:
            self.threshold_unit = threshold_unit
        if cycle_type is not APIHelper.SKIP:
            self.cycle_type = cycle_type
        if allowance_threshold is not APIHelper.SKIP:
            self.allowance_threshold = allowance_threshold
        if device_group is not APIHelper.SKIP:
            self.device_group = device_group
        if account_group_share is not APIHelper.SKIP:
            self.account_group_share = account_group_share

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        filter_criteria =\
            AccountLevelFilter.from_dictionary(
                dictionary.get("filterCriteria"))\
                if "filterCriteria" in dictionary.keys()\
                else APIHelper.SKIP
        condition = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DataTrigger5Condition"),
            dictionary.get("condition"),
            False)\
            if dictionary.get("condition") is not None\
            else APIHelper.SKIP
        action =\
            dictionary.get("action")\
            if dictionary.get("action")\
                else APIHelper.SKIP
        condition_type =\
            dictionary.get("conditionType")\
            if dictionary.get("conditionType")\
                else APIHelper.SKIP
        comparitor =\
            dictionary.get("comparitor")\
            if dictionary.get("comparitor")\
                else APIHelper.SKIP
        threshold =\
            dictionary.get("threshold")\
            if dictionary.get("threshold")\
                else APIHelper.SKIP
        threshold_unit =\
            dictionary.get("thresholdUnit")\
            if dictionary.get("thresholdUnit")\
                else APIHelper.SKIP
        cycle_type =\
            dictionary.get("cycleType")\
            if dictionary.get("cycleType")\
                else APIHelper.SKIP
        allowance_threshold =\
            AllowanceThreshold.from_dictionary(
                dictionary.get("allowanceThreshold"))\
                if "allowanceThreshold" in dictionary.keys()\
                else APIHelper.SKIP
        device_group =\
            DeviceGroupFilterCriteria.from_dictionary(
                dictionary.get("deviceGroup"))\
                if "deviceGroup" in dictionary.keys()\
                else APIHelper.SKIP
        account_group_share =\
            AccountGroupShareIndividual1.from_dictionary(
                dictionary.get("accountGroupShare"))\
                if "accountGroupShare" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(filter_criteria,
                   condition,
                   action,
                   condition_type,
                   comparitor,
                   threshold,
                   threshold_unit,
                   cycle_type,
                   allowance_threshold,
                   device_group,
                   account_group_share)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _filter_criteria=(
            self.filter_criteria
            if hasattr(self, "filter_criteria")
            else None
        )
        _condition=(
            self.condition
            if hasattr(self, "condition")
            else None
        )
        _action=(
            self.action
            if hasattr(self, "action")
            else None
        )
        _condition_type=(
            self.condition_type
            if hasattr(self, "condition_type")
            else None
        )
        _comparitor=(
            self.comparitor
            if hasattr(self, "comparitor")
            else None
        )
        _threshold=(
            self.threshold
            if hasattr(self, "threshold")
            else None
        )
        _threshold_unit=(
            self.threshold_unit
            if hasattr(self, "threshold_unit")
            else None
        )
        _cycle_type=(
            self.cycle_type
            if hasattr(self, "cycle_type")
            else None
        )
        _allowance_threshold=(
            self.allowance_threshold
            if hasattr(self, "allowance_threshold")
            else None
        )
        _device_group=(
            self.device_group
            if hasattr(self, "device_group")
            else None
        )
        _account_group_share=(
            self.account_group_share
            if hasattr(self, "account_group_share")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"filter_criteria={_filter_criteria!r}, "
            f"condition={_condition!r}, "
            f"action={_action!r}, "
            f"condition_type={_condition_type!r}, "
            f"comparitor={_comparitor!r}, "
            f"threshold={_threshold!r}, "
            f"threshold_unit={_threshold_unit!r}, "
            f"cycle_type={_cycle_type!r}, "
            f"allowance_threshold={_allowance_threshold!r}, "
            f"device_group={_device_group!r}, "
            f"account_group_share={_account_group_share!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _filter_criteria=(
            self.filter_criteria
            if hasattr(self, "filter_criteria")
            else None
        )
        _condition=(
            self.condition
            if hasattr(self, "condition")
            else None
        )
        _action=(
            self.action
            if hasattr(self, "action")
            else None
        )
        _condition_type=(
            self.condition_type
            if hasattr(self, "condition_type")
            else None
        )
        _comparitor=(
            self.comparitor
            if hasattr(self, "comparitor")
            else None
        )
        _threshold=(
            self.threshold
            if hasattr(self, "threshold")
            else None
        )
        _threshold_unit=(
            self.threshold_unit
            if hasattr(self, "threshold_unit")
            else None
        )
        _cycle_type=(
            self.cycle_type
            if hasattr(self, "cycle_type")
            else None
        )
        _allowance_threshold=(
            self.allowance_threshold
            if hasattr(self, "allowance_threshold")
            else None
        )
        _device_group=(
            self.device_group
            if hasattr(self, "device_group")
            else None
        )
        _account_group_share=(
            self.account_group_share
            if hasattr(self, "account_group_share")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"filter_criteria={_filter_criteria!s}, "
            f"condition={_condition!s}, "
            f"action={_action!s}, "
            f"condition_type={_condition_type!s}, "
            f"comparitor={_comparitor!s}, "
            f"threshold={_threshold!s}, "
            f"threshold_unit={_threshold_unit!s}, "
            f"cycle_type={_cycle_type!s}, "
            f"allowance_threshold={_allowance_threshold!s}, "
            f"device_group={_device_group!s}, "
            f"account_group_share={_account_group_share!s}, "
            f")"
        )
