"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.grass import Grass


class DescriptionOfRoadSurfaceGrass(object):
    """Implementation of the 'DescriptionOfRoadSurface_Grass' model.

    Attributes:
        grass (Grass): Indicates the surface of the roadway is grass.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "grass": "grass",
    }

    def __init__(
        self,
        grass=None):
        """Initialize a DescriptionOfRoadSurfaceGrass instance."""
        # Initialize members of the class
        self.grass = grass

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        grass =\
            Grass.from_dictionary(
                dictionary.get("grass"))\
                if dictionary.get("grass") else None

        # Return an object of this model
        return cls(grass)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.grass,
                    type_callable=lambda value:
                        Grass.validate(value),
                    is_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("grass"),
                type_callable=lambda value:
                    Grass.validate(value),
                is_model_dict=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _grass=self.grass
        return (
            f"{self.__class__.__name__}("
            f"grass={_grass!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _grass=self.grass
        return (
            f"{self.__class__.__name__}("
            f"grass={_grass!s}, "
            f")"
        )
