"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class DeviceId2(object):
    """Implementation of the 'DeviceId2' model.

    Attributes:
        id (str): The model property of type str.
        kind (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "kind": "kind",
    }

    _optionals = [
        "id",
        "kind",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        kind=APIHelper.SKIP):
        """Initialize a DeviceId2 instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if kind is not APIHelper.SKIP:
            self.kind = kind

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        kind =\
            dictionary.get("kind")\
            if dictionary.get("kind")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   kind)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _kind=(
            self.kind
            if hasattr(self, "kind")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"kind={_kind!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _kind=(
            self.kind
            if hasattr(self, "kind")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"kind={_kind!s}, "
            f")"
        )
