"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.models.pwn_device_id import PWNDeviceId


class DeviceListIP(object):
    """Implementation of the 'DeviceListIP' model.

    Attributes:
        device_ids (List[PWNDeviceId]): The model property of type List[PWNDeviceId].
        ipaddress (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_ids": "deviceIds",
        "ipaddress": "ipAddress",
    }

    def __init__(
        self,
        device_ids=None,
        ipaddress=None):
        """Initialize a DeviceListIP instance."""
        # Initialize members of the class
        self.device_ids = device_ids
        self.ipaddress = ipaddress

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        device_ids = None
        if dictionary.get("deviceIds") is not None:
            device_ids = [
                PWNDeviceId.from_dictionary(x)
                    for x in dictionary.get("deviceIds")
            ]
        ipaddress =\
            dictionary.get("ipAddress")\
            if dictionary.get("ipAddress")\
                else None

        # Return an object of this model
        return cls(device_ids,
                   ipaddress)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _device_ids=self.device_ids
        _ipaddress=self.ipaddress
        return (
            f"{self.__class__.__name__}("
            f"device_ids={_device_ids!r}, "
            f"ipaddress={_ipaddress!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _device_ids=self.device_ids
        _ipaddress=self.ipaddress
        return (
            f"{self.__class__.__name__}("
            f"device_ids={_device_ids!s}, "
            f"ipaddress={_ipaddress!s}, "
            f")"
        )
