"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class Devicepropertyselection(object):
    """Implementation of the 'devicepropertyselection' model.

    Attributes:
        modelid (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "modelid": "modelid",
    }

    _optionals = [
        "modelid",
    ]

    def __init__(
        self,
        modelid=APIHelper.SKIP):
        """Initialize a Devicepropertyselection instance."""
        # Initialize members of the class
        if modelid is not APIHelper.SKIP:
            self.modelid = modelid

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        modelid =\
            dictionary.get("modelid")\
            if dictionary.get("modelid")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(modelid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _modelid=(
            self.modelid
            if hasattr(self, "modelid")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"modelid={_modelid!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _modelid=(
            self.modelid
            if hasattr(self, "modelid")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"modelid={_modelid!s}, "
            f")"
        )
