"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class DeviceLabels(object):
    """Implementation of the 'DeviceLabels' model.

    A label for a single device.

    Attributes:
        name (str): The label you want to associate with the device.
        value (str): The value of label

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "value": "value",
    }

    def __init__(
        self,
        name=None,
        value=None):
        """Initialize a DeviceLabels instance."""
        # Initialize members of the class
        self.name = name
        self.value = value

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None

        # Return an object of this model
        return cls(name,
                   value)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.name,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.value,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("name"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("value"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _value=self.value
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"value={_value!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _value=self.value
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"value={_value!s}, "
            f")"
        )
