"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.models.hpl_bullseye_enable import (
    HplBullseyeEnable,
)


class DeviceServiceRequest(object):
    """Implementation of the 'DeviceServiceRequest' model.

    Device information.

    Attributes:
        imei (str): The International Mobile Equipment Identifier of the device.
        bullseye_enable (HplBullseyeEnable): A flag that shows if Hyper Precise is
            enabled (true) or disabled (false).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "imei": "imei",
        "bullseye_enable": "BullseyeEnable",
    }

    def __init__(
        self,
        imei=None,
        bullseye_enable=None):
        """Initialize a DeviceServiceRequest instance."""
        # Initialize members of the class
        self.imei = imei
        self.bullseye_enable = bullseye_enable

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        imei =\
            dictionary.get("imei")\
            if dictionary.get("imei")\
                else None
        bullseye_enable =\
            HplBullseyeEnable.from_dictionary(
                dictionary.get("BullseyeEnable"))\
                if dictionary.get("BullseyeEnable") else None

        # Return an object of this model
        return cls(imei,
                   bullseye_enable)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _imei=self.imei
        _bullseye_enable=self.bullseye_enable
        return (
            f"{self.__class__.__name__}("
            f"imei={_imei!r}, "
            f"bullseye_enable={_bullseye_enable!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _imei=self.imei
        _bullseye_enable=self.bullseye_enable
        return (
            f"{self.__class__.__name__}("
            f"imei={_imei!s}, "
            f"bullseye_enable={_bullseye_enable!s}, "
            f")"
        )
