"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class DropResponseItem(object):
    """Implementation of the 'Drop Response Item' model.

    Attributes:
        imei (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "imei": "imei",
    }

    _optionals = [
        "imei",
    ]

    def __init__(
        self,
        imei=APIHelper.SKIP):
        """Initialize a DropResponseItem instance."""
        # Initialize members of the class
        if imei is not APIHelper.SKIP:
            self.imei = imei

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        imei =\
            dictionary.get("imei")\
            if dictionary.get("imei")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(imei)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _imei=(
            self.imei
            if hasattr(self, "imei")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"imei={_imei!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _imei=(
            self.imei
            if hasattr(self, "imei")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"imei={_imei!s}, "
            f")"
        )
