"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.dto_profile import DtoProfile


class DtoConfigurationProfile(object):
    """Implementation of the 'dto.configurationProfile' model.

    Attributes:
        accountname (str): The numeric account name, which must include leading zeros
        profiles (List[DtoProfile]): The model property of type List[DtoProfile].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "accountname": "accountname",
        "profiles": "profiles",
    }

    _optionals = [
        "accountname",
        "profiles",
    ]

    def __init__(
        self,
        accountname=APIHelper.SKIP,
        profiles=APIHelper.SKIP):
        """Initialize a DtoConfigurationProfile instance."""
        # Initialize members of the class
        if accountname is not APIHelper.SKIP:
            self.accountname = accountname
        if profiles is not APIHelper.SKIP:
            self.profiles = profiles

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        accountname =\
            dictionary.get("accountname")\
            if dictionary.get("accountname")\
                else APIHelper.SKIP
        profiles = None
        if dictionary.get("profiles") is not None:
            profiles = [
                DtoProfile.from_dictionary(x)
                    for x in dictionary.get("profiles")
            ]
        else:
            profiles = APIHelper.SKIP

        # Return an object of this model
        return cls(accountname,
                   profiles)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _accountname=(
            self.accountname
            if hasattr(self, "accountname")
            else None
        )
        _profiles=(
            self.profiles
            if hasattr(self, "profiles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"accountname={_accountname!r}, "
            f"profiles={_profiles!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _accountname=(
            self.accountname
            if hasattr(self, "accountname")
            else None
        )
        _profiles=(
            self.profiles
            if hasattr(self, "profiles")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"accountname={_accountname!s}, "
            f"profiles={_profiles!s}, "
            f")"
        )
