"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class DtoQueryMetricsResponse(object):
    """Implementation of the 'dto.queryMetricsResponse' model.

    Attributes:
        critical (int): The number of critical alerts in the queried time period
        major (int): The number of major alerts in the queried time period
        minor (int): The number of minor alerts in the queried time period
        noalert (int): The number of sensor reports containing no  alerts in the
            queried time period
        total (int): The total number of alerts in the queried time period
        deltacritical (int): The change in the number of critical alerts in the
            queried time period
        deltamajor (int): The change in the number of major alerts in the queried
            time period
        deltaminor (int): The change in the number of minor alerts in the queried
            time period
        deltanoalert (int): The change in the number of sensor reports containing no
            alerts in the queried time period

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "critical": "critical",
        "major": "major",
        "minor": "minor",
        "noalert": "noalert",
        "total": "total",
        "deltacritical": "deltacritical",
        "deltamajor": "deltamajor",
        "deltaminor": "deltaminor",
        "deltanoalert": "deltanoalert",
    }

    _optionals = [
        "critical",
        "major",
        "minor",
        "noalert",
        "total",
        "deltacritical",
        "deltamajor",
        "deltaminor",
        "deltanoalert",
    ]

    def __init__(
        self,
        critical=APIHelper.SKIP,
        major=APIHelper.SKIP,
        minor=APIHelper.SKIP,
        noalert=APIHelper.SKIP,
        total=APIHelper.SKIP,
        deltacritical=APIHelper.SKIP,
        deltamajor=APIHelper.SKIP,
        deltaminor=APIHelper.SKIP,
        deltanoalert=APIHelper.SKIP):
        """Initialize a DtoQueryMetricsResponse instance."""
        # Initialize members of the class
        if critical is not APIHelper.SKIP:
            self.critical = critical
        if major is not APIHelper.SKIP:
            self.major = major
        if minor is not APIHelper.SKIP:
            self.minor = minor
        if noalert is not APIHelper.SKIP:
            self.noalert = noalert
        if total is not APIHelper.SKIP:
            self.total = total
        if deltacritical is not APIHelper.SKIP:
            self.deltacritical = deltacritical
        if deltamajor is not APIHelper.SKIP:
            self.deltamajor = deltamajor
        if deltaminor is not APIHelper.SKIP:
            self.deltaminor = deltaminor
        if deltanoalert is not APIHelper.SKIP:
            self.deltanoalert = deltanoalert

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        critical =\
            dictionary.get("critical")\
            if dictionary.get("critical")\
                else APIHelper.SKIP
        major =\
            dictionary.get("major")\
            if dictionary.get("major")\
                else APIHelper.SKIP
        minor =\
            dictionary.get("minor")\
            if dictionary.get("minor")\
                else APIHelper.SKIP
        noalert =\
            dictionary.get("noalert")\
            if dictionary.get("noalert")\
                else APIHelper.SKIP
        total =\
            dictionary.get("total")\
            if dictionary.get("total")\
                else APIHelper.SKIP
        deltacritical =\
            dictionary.get("deltacritical")\
            if dictionary.get("deltacritical")\
                else APIHelper.SKIP
        deltamajor =\
            dictionary.get("deltamajor")\
            if dictionary.get("deltamajor")\
                else APIHelper.SKIP
        deltaminor =\
            dictionary.get("deltaminor")\
            if dictionary.get("deltaminor")\
                else APIHelper.SKIP
        deltanoalert =\
            dictionary.get("deltanoalert")\
            if dictionary.get("deltanoalert")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(critical,
                   major,
                   minor,
                   noalert,
                   total,
                   deltacritical,
                   deltamajor,
                   deltaminor,
                   deltanoalert)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _critical=(
            self.critical
            if hasattr(self, "critical")
            else None
        )
        _major=(
            self.major
            if hasattr(self, "major")
            else None
        )
        _minor=(
            self.minor
            if hasattr(self, "minor")
            else None
        )
        _noalert=(
            self.noalert
            if hasattr(self, "noalert")
            else None
        )
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _deltacritical=(
            self.deltacritical
            if hasattr(self, "deltacritical")
            else None
        )
        _deltamajor=(
            self.deltamajor
            if hasattr(self, "deltamajor")
            else None
        )
        _deltaminor=(
            self.deltaminor
            if hasattr(self, "deltaminor")
            else None
        )
        _deltanoalert=(
            self.deltanoalert
            if hasattr(self, "deltanoalert")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"critical={_critical!r}, "
            f"major={_major!r}, "
            f"minor={_minor!r}, "
            f"noalert={_noalert!r}, "
            f"total={_total!r}, "
            f"deltacritical={_deltacritical!r}, "
            f"deltamajor={_deltamajor!r}, "
            f"deltaminor={_deltaminor!r}, "
            f"deltanoalert={_deltanoalert!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _critical=(
            self.critical
            if hasattr(self, "critical")
            else None
        )
        _major=(
            self.major
            if hasattr(self, "major")
            else None
        )
        _minor=(
            self.minor
            if hasattr(self, "minor")
            else None
        )
        _noalert=(
            self.noalert
            if hasattr(self, "noalert")
            else None
        )
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _deltacritical=(
            self.deltacritical
            if hasattr(self, "deltacritical")
            else None
        )
        _deltamajor=(
            self.deltamajor
            if hasattr(self, "deltamajor")
            else None
        )
        _deltaminor=(
            self.deltaminor
            if hasattr(self, "deltaminor")
            else None
        )
        _deltanoalert=(
            self.deltanoalert
            if hasattr(self, "deltanoalert")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"critical={_critical!s}, "
            f"major={_major!s}, "
            f"minor={_minor!s}, "
            f"noalert={_noalert!s}, "
            f"total={_total!s}, "
            f"deltacritical={_deltacritical!s}, "
            f"deltamajor={_deltamajor!s}, "
            f"deltaminor={_deltaminor!s}, "
            f"deltanoalert={_deltanoalert!s}, "
            f")"
        )
