"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.dto_resourceidentifier import (
    DtoResourceidentifier,
)
from verizon.models.rbstiltconfig import Rbstiltconfig


class DtoDeviceCommand(object):
    """Implementation of the 'dto.deviceCommand' model.

    Attributes:
        account_name (str): The numeric account name, which must include leading zeros
        configuration (Rbstiltconfig): The model property of type Rbstiltconfig.
        resourceidentifier (DtoResourceidentifier): The model property of type
            DtoResourceidentifier.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_name": "accountName",
        "configuration": "configuration",
        "resourceidentifier": "resourceidentifier",
    }

    _optionals = [
        "account_name",
        "configuration",
        "resourceidentifier",
    ]

    def __init__(
        self,
        account_name=APIHelper.SKIP,
        configuration=APIHelper.SKIP,
        resourceidentifier=APIHelper.SKIP):
        """Initialize a DtoDeviceCommand instance."""
        # Initialize members of the class
        if account_name is not APIHelper.SKIP:
            self.account_name = account_name
        if configuration is not APIHelper.SKIP:
            self.configuration = configuration
        if resourceidentifier is not APIHelper.SKIP:
            self.resourceidentifier = resourceidentifier

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_name =\
            dictionary.get("accountName")\
            if dictionary.get("accountName")\
                else APIHelper.SKIP
        configuration =\
            Rbstiltconfig.from_dictionary(
                dictionary.get("configuration"))\
                if "configuration" in dictionary.keys()\
                else APIHelper.SKIP
        resourceidentifier =\
            DtoResourceidentifier.from_dictionary(
                dictionary.get("resourceidentifier"))\
                if "resourceidentifier" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_name,
                   configuration,
                   resourceidentifier)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_name=(
            self.account_name
            if hasattr(self, "account_name")
            else None
        )
        _configuration=(
            self.configuration
            if hasattr(self, "configuration")
            else None
        )
        _resourceidentifier=(
            self.resourceidentifier
            if hasattr(self, "resourceidentifier")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_name={_account_name!r}, "
            f"configuration={_configuration!r}, "
            f"resourceidentifier={_resourceidentifier!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_name=(
            self.account_name
            if hasattr(self, "account_name")
            else None
        )
        _configuration=(
            self.configuration
            if hasattr(self, "configuration")
            else None
        )
        _resourceidentifier=(
            self.resourceidentifier
            if hasattr(self, "resourceidentifier")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_name={_account_name!s}, "
            f"configuration={_configuration!s}, "
            f"resourceidentifier={_resourceidentifier!s}, "
            f")"
        )
