"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.action_resultwith_device_config import (
    ActionResultwithDeviceConfig,
)


class DtoDeviceActionSetResponse(object):
    """Implementation of the 'dto.DeviceActionSetResponse' model.

    Attributes:
        actionresult (List[ActionResultwithDeviceConfig]): The model property of type
            List[ActionResultwithDeviceConfig].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "actionresult": "actionresult",
    }

    _optionals = [
        "actionresult",
    ]

    def __init__(
        self,
        actionresult=APIHelper.SKIP):
        """Initialize a DtoDeviceActionSetResponse instance."""
        # Initialize members of the class
        if actionresult is not APIHelper.SKIP:
            self.actionresult = actionresult

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        actionresult = None
        if dictionary.get("actionresult") is not None:
            actionresult = [
                ActionResultwithDeviceConfig.from_dictionary(x)
                    for x in dictionary.get("actionresult")
            ]
        else:
            actionresult = APIHelper.SKIP

        # Return an object of this model
        return cls(actionresult)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _actionresult=(
            self.actionresult
            if hasattr(self, "actionresult")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"actionresult={_actionresult!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _actionresult=(
            self.actionresult
            if hasattr(self, "actionresult")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"actionresult={_actionresult!s}, "
            f")"
        )
