"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.dto_sensor_boarding_event import (
    DtoSensorBoardingEvent,
)


class DtoSensorOnBoardingStatusResponse(object):
    """Implementation of the 'dto.SensorOnBoardingStatusResponse' model.

    Attributes:
        events (List[DtoSensorBoardingEvent]): The model property of type
            List[DtoSensorBoardingEvent].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "events": "events",
    }

    _optionals = [
        "events",
    ]

    def __init__(
        self,
        events=APIHelper.SKIP):
        """Initialize a DtoSensorOnBoardingStatusResponse instance."""
        # Initialize members of the class
        if events is not APIHelper.SKIP:
            self.events = events

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        events = None
        if dictionary.get("events") is not None:
            events = [
                DtoSensorBoardingEvent.from_dictionary(x)
                    for x in dictionary.get("events")
            ]
        else:
            events = APIHelper.SKIP

        # Return an object of this model
        return cls(events)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"events={_events!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"events={_events!s}, "
            f")"
        )
