"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class DtoProfileResponse(object):
    """Implementation of the 'dto.profileResponse' model.

    Attributes:
        id (str): The model property of type str.
        kind (str): the user defined profile kind
        version (str): The resource version
        versionid (str): The model property of type str.
        createdon (datetime): Timestamp of the record
        lastupdated (datetime): Timestamp of the record
        name (str): user defined profile name
        foreignid (str): UUID of the ECPD account the user belongs to
        billingaccountid (str): The billing account ID. This is the same value as the
            Account ID
        modelid (str): device model id
        configuration (Any): The model property of type Any.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "kind": "kind",
        "version": "version",
        "versionid": "versionid",
        "createdon": "createdon",
        "lastupdated": "lastupdated",
        "name": "name",
        "foreignid": "foreignid",
        "billingaccountid": "billingaccountid",
        "modelid": "modelid",
        "configuration": "configuration",
    }

    _optionals = [
        "id",
        "kind",
        "version",
        "versionid",
        "createdon",
        "lastupdated",
        "name",
        "foreignid",
        "billingaccountid",
        "modelid",
        "configuration",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        kind=APIHelper.SKIP,
        version=APIHelper.SKIP,
        versionid=APIHelper.SKIP,
        createdon=APIHelper.SKIP,
        lastupdated=APIHelper.SKIP,
        name=APIHelper.SKIP,
        foreignid=APIHelper.SKIP,
        billingaccountid=APIHelper.SKIP,
        modelid=APIHelper.SKIP,
        configuration=APIHelper.SKIP):
        """Initialize a DtoProfileResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if kind is not APIHelper.SKIP:
            self.kind = kind
        if version is not APIHelper.SKIP:
            self.version = version
        if versionid is not APIHelper.SKIP:
            self.versionid = versionid
        if createdon is not APIHelper.SKIP:
            self.createdon =\
                 APIHelper.apply_datetime_converter(
                createdon, APIHelper.RFC3339DateTime)\
                 if createdon else None
        if lastupdated is not APIHelper.SKIP:
            self.lastupdated =\
                 APIHelper.apply_datetime_converter(
                lastupdated, APIHelper.RFC3339DateTime)\
                 if lastupdated else None
        if name is not APIHelper.SKIP:
            self.name = name
        if foreignid is not APIHelper.SKIP:
            self.foreignid = foreignid
        if billingaccountid is not APIHelper.SKIP:
            self.billingaccountid = billingaccountid
        if modelid is not APIHelper.SKIP:
            self.modelid = modelid
        if configuration is not APIHelper.SKIP:
            self.configuration = configuration

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        kind =\
            dictionary.get("kind")\
            if dictionary.get("kind")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP
        versionid =\
            dictionary.get("versionid")\
            if dictionary.get("versionid")\
                else APIHelper.SKIP
        createdon = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("createdon")).datetime\
            if dictionary.get("createdon") else APIHelper.SKIP
        lastupdated = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("lastupdated")).datetime\
            if dictionary.get("lastupdated") else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        foreignid =\
            dictionary.get("foreignid")\
            if dictionary.get("foreignid")\
                else APIHelper.SKIP
        billingaccountid =\
            dictionary.get("billingaccountid")\
            if dictionary.get("billingaccountid")\
                else APIHelper.SKIP
        modelid =\
            dictionary.get("modelid")\
            if dictionary.get("modelid")\
                else APIHelper.SKIP
        configuration =\
            dictionary.get("configuration")\
            if dictionary.get("configuration")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(id,
                   kind,
                   version,
                   versionid,
                   createdon,
                   lastupdated,
                   name,
                   foreignid,
                   billingaccountid,
                   modelid,
                   configuration)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _kind=(
            self.kind
            if hasattr(self, "kind")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _versionid=(
            self.versionid
            if hasattr(self, "versionid")
            else None
        )
        _createdon=(
            self.createdon
            if hasattr(self, "createdon")
            else None
        )
        _lastupdated=(
            self.lastupdated
            if hasattr(self, "lastupdated")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _foreignid=(
            self.foreignid
            if hasattr(self, "foreignid")
            else None
        )
        _billingaccountid=(
            self.billingaccountid
            if hasattr(self, "billingaccountid")
            else None
        )
        _modelid=(
            self.modelid
            if hasattr(self, "modelid")
            else None
        )
        _configuration=(
            self.configuration
            if hasattr(self, "configuration")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"kind={_kind!r}, "
            f"version={_version!r}, "
            f"versionid={_versionid!r}, "
            f"createdon={_createdon!r}, "
            f"lastupdated={_lastupdated!r}, "
            f"name={_name!r}, "
            f"foreignid={_foreignid!r}, "
            f"billingaccountid={_billingaccountid!r}, "
            f"modelid={_modelid!r}, "
            f"configuration={_configuration!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _kind=(
            self.kind
            if hasattr(self, "kind")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _versionid=(
            self.versionid
            if hasattr(self, "versionid")
            else None
        )
        _createdon=(
            self.createdon
            if hasattr(self, "createdon")
            else None
        )
        _lastupdated=(
            self.lastupdated
            if hasattr(self, "lastupdated")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _foreignid=(
            self.foreignid
            if hasattr(self, "foreignid")
            else None
        )
        _billingaccountid=(
            self.billingaccountid
            if hasattr(self, "billingaccountid")
            else None
        )
        _modelid=(
            self.modelid
            if hasattr(self, "modelid")
            else None
        )
        _configuration=(
            self.configuration
            if hasattr(self, "configuration")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"kind={_kind!s}, "
            f"version={_version!s}, "
            f"versionid={_versionid!s}, "
            f"createdon={_createdon!s}, "
            f"lastupdated={_lastupdated!s}, "
            f"name={_name!s}, "
            f"foreignid={_foreignid!s}, "
            f"billingaccountid={_billingaccountid!s}, "
            f"modelid={_modelid!s}, "
            f"configuration={_configuration!s}, "
            f")"
        )
