"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.sensor_insights_ble import (
    SensorInsightsBLE,
)


class DtoDeviceConfig(object):
    """Implementation of the 'dto.deviceConfig' model.

    Attributes:
        ble (SensorInsightsBLE): Property objects for Bluetooth Low-Energy (BLE)
            devices

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ble": "ble",
    }

    _optionals = [
        "ble",
    ]

    def __init__(
        self,
        ble=APIHelper.SKIP):
        """Initialize a DtoDeviceConfig instance."""
        # Initialize members of the class
        if ble is not APIHelper.SKIP:
            self.ble = ble

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ble =\
            SensorInsightsBLE.from_dictionary(
                dictionary.get("ble"))\
                if "ble" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(ble)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ble=(
            self.ble
            if hasattr(self, "ble")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"ble={_ble!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ble=(
            self.ble
            if hasattr(self, "ble")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"ble={_ble!s}, "
            f")"
        )
