"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class ETXClientIDLookup(object):
    """Implementation of the 'ETXClientIDLookup' model.

    Lookup object for identifying an ETX client. One of the following IDs is
    required: DeviceID, IMEI, ICCID, or IMSI. If more than one ID is provided, the
    API will use the first ID found in the following order: DeviceID, IMEI, ICCID,
    IMSI.

    Attributes:
        device_id (uuid|str): The generated ID (UUID v4) for the device. It can be
            used as:   - the MQTT Client ID when connecting to the Message Exchange
            system   - a parameter when asking for the connection endpoint   - a
            parameter when finishing the device registration   - a parameter when
            unregistering the device
        imei (str): The IMEI number of the device.
        iccid (str): The ICCID number of the device.
        imsi (str): The IMSI number of the device.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_id": "DeviceID",
        "imei": "IMEI",
        "iccid": "ICCID",
        "imsi": "IMSI",
    }

    _optionals = [
        "device_id",
        "imei",
        "iccid",
        "imsi",
    ]

    def __init__(
        self,
        device_id=APIHelper.SKIP,
        imei=APIHelper.SKIP,
        iccid=APIHelper.SKIP,
        imsi=APIHelper.SKIP):
        """Initialize a ETXClientIDLookup instance."""
        # Initialize members of the class
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id
        if imei is not APIHelper.SKIP:
            self.imei = imei
        if iccid is not APIHelper.SKIP:
            self.iccid = iccid
        if imsi is not APIHelper.SKIP:
            self.imsi = imsi

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        device_id =\
            dictionary.get("DeviceID")\
            if dictionary.get("DeviceID")\
                else APIHelper.SKIP
        imei =\
            dictionary.get("IMEI")\
            if dictionary.get("IMEI")\
                else APIHelper.SKIP
        iccid =\
            dictionary.get("ICCID")\
            if dictionary.get("ICCID")\
                else APIHelper.SKIP
        imsi =\
            dictionary.get("IMSI")\
            if dictionary.get("IMSI")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(device_id,
                   imei,
                   iccid,
                   imsi)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _imei=(
            self.imei
            if hasattr(self, "imei")
            else None
        )
        _iccid=(
            self.iccid
            if hasattr(self, "iccid")
            else None
        )
        _imsi=(
            self.imsi
            if hasattr(self, "imsi")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"device_id={_device_id!r}, "
            f"imei={_imei!r}, "
            f"iccid={_iccid!r}, "
            f"imsi={_imsi!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _device_id=(
            self.device_id
            if hasattr(self, "device_id")
            else None
        )
        _imei=(
            self.imei
            if hasattr(self, "imei")
            else None
        )
        _iccid=(
            self.iccid
            if hasattr(self, "iccid")
            else None
        )
        _imsi=(
            self.imsi
            if hasattr(self, "imsi")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"device_id={_device_id!s}, "
            f"imei={_imei!s}, "
            f"iccid={_iccid!s}, "
            f"imsi={_imsi!s}, "
            f")"
        )
