"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class EventType(object):
    """Implementation of the 'EventType' model.

    The type of event including direct and sub cause.

    Attributes:
        cc_and_scc (TrafficConditionCauseCode | AccidentCauseCode |
            RoadworksCauseCode | ImpassabilityCauseCode | WrongWayDrivingCauseCode |
            EmergencyVehicleApproachingCauseCode | None): The main cause of a
            detected event. Each entry is of a different type and represents the sub
            cause code.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cc_and_scc": "ccAndScc",
    }

    _optionals = [
        "cc_and_scc",
    ]

    def __init__(
        self,
        cc_and_scc=APIHelper.SKIP):
        """Initialize a EventType instance."""
        # Initialize members of the class
        if cc_and_scc is not APIHelper.SKIP:
            self.cc_and_scc = cc_and_scc

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        cc_and_scc = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("CauseCodeChoice"),
            dictionary.get("ccAndScc"),
            False)\
            if dictionary.get("ccAndScc") is not None\
            else APIHelper.SKIP

        # Return an object of this model
        return cls(cc_and_scc)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _cc_and_scc=(
            self.cc_and_scc
            if hasattr(self, "cc_and_scc")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"cc_and_scc={_cc_and_scc!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _cc_and_scc=(
            self.cc_and_scc
            if hasattr(self, "cc_and_scc")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"cc_and_scc={_cc_and_scc!s}, "
            f")"
        )
