"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class FrictionInformation(object):
    """Implementation of the 'FrictionInformation' model.

    Attributes:
        road_surface_description (DescriptionOfRoadSurfacePortlandCement |
            DescriptionOfRoadSurfaceAsphaltOrTar | DescriptionOfRoadSurfaceGravel |
            DescriptionOfRoadSurfaceGrass | DescriptionOfRoadSurfaceCinders |
            DescriptionOfRoadSurfaceRock | DescriptionOfRoadSurfaceIce |
            DescriptionOfRoadSurfaceSnow): Indicates the composition of the surface
            of the roadway for use in estimation of friction.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "road_surface_description": "roadSurfaceDescription",
    }

    def __init__(
        self,
        road_surface_description=None):
        """Initialize a FrictionInformation instance."""
        # Initialize members of the class
        self.road_surface_description = road_surface_description

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        road_surface_description = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("DescriptionOfRoadSurface"),
            dictionary.get("roadSurfaceDescription"),
            False)\
            if dictionary.get("roadSurfaceDescription") is not None\
            else None

        # Return an object of this model
        return cls(road_surface_description)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return (UnionTypeLookUp.get("DescriptionOfRoadSurface")
                .validate(dictionary.road_surface_description).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return (UnionTypeLookUp.get("DescriptionOfRoadSurface")
            .validate(dictionary.get("roadSurfaceDescription")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _road_surface_description=self.road_surface_description
        return (
            f"{self.__class__.__name__}("
            f"road_surface_description={_road_surface_description!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _road_surface_description=self.road_surface_description
        return (
            f"{self.__class__.__name__}("
            f"road_surface_description={_road_surface_description!s}, "
            f")"
        )
