"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.models.generic_payload import GenericPayload


class GenericMessage(object):
    """Implementation of the 'GenericMessage' model.

    A message carrying a generic (custom) V2X payload.

    Attributes:
        generic (GenericPayload): Custom message which is defined by the user and can
            support "any" message type or format.  **Note:** ETX prefers the j2735 or
            the j2735_gr encoding and only vendor specific message types are allowed
            to be published in different message formats.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "generic": "generic",
    }

    def __init__(
        self,
        generic=None):
        """Initialize a GenericMessage instance."""
        # Initialize members of the class
        self.generic = generic

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        generic =\
            GenericPayload.from_dictionary(
                dictionary.get("generic"))\
                if dictionary.get("generic") else None

        # Return an object of this model
        return cls(generic)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _generic=self.generic
        return (
            f"{self.__class__.__name__}("
            f"generic={_generic!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _generic=self.generic
        return (
            f"{self.__class__.__name__}("
            f"generic={_generic!s}, "
            f")"
        )
