"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.generate_response_item_credential import (
    GenerateResponseItemCredential,
)


class GenerateResponseItem(object):
    """Implementation of the 'Generate Response Item' model.

    Attributes:
        imei (str): The model property of type str.
        credential (GenerateResponseItemCredential): The model property of type
            GenerateResponseItemCredential.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "imei": "imei",
        "credential": "credential",
    }

    _optionals = [
        "imei",
        "credential",
    ]

    def __init__(
        self,
        imei=APIHelper.SKIP,
        credential=APIHelper.SKIP):
        """Initialize a GenerateResponseItem instance."""
        # Initialize members of the class
        if imei is not APIHelper.SKIP:
            self.imei = imei
        if credential is not APIHelper.SKIP:
            self.credential = credential

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        imei =\
            dictionary.get("imei")\
            if dictionary.get("imei")\
                else APIHelper.SKIP
        credential =\
            GenerateResponseItemCredential.from_dictionary(
                dictionary.get("credential"))\
                if "credential" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(imei,
                   credential)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _imei=(
            self.imei
            if hasattr(self, "imei")
            else None
        )
        _credential=(
            self.credential
            if hasattr(self, "credential")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"imei={_imei!r}, "
            f"credential={_credential!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _imei=(
            self.imei
            if hasattr(self, "imei")
            else None
        )
        _credential=(
            self.credential
            if hasattr(self, "credential")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"imei={_imei!s}, "
            f"credential={_credential!s}, "
            f")"
        )
