"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.ip_poolforplanner import (
    IPPoolforplanner,
)
from verizon.models.service_plan_responseforplanner import (
    ServicePlanResponseforplanner,
)


class GetAccountInformationResponseforplanner(object):
    """Implementation of the 'GetAccountInformationResponseforplanner' model.

    Attributes:
        account_name (str): The model property of type str.
        account_number (str): The numeric name of the account, including leading
            zeros.
        carriers (List[str]): The list of carrier names with profiles.
        features (List[str]): a list of features associated with the resident
            profiles.
        ip_pools (List[IPPoolforplanner]): The model property of type
            List[IPPoolforplanner].
        is_provisioning_allowed (bool): A flag indicating if provisioning is allowed
            (true) or provisioning is locked (false).
        organization_name (str): The user assigned organization name.
        service_plans (List[ServicePlanResponseforplanner]): A list of service plans
            associated with the resident profiles.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_name": "accountName",
        "account_number": "accountNumber",
        "carriers": "carriers",
        "features": "features",
        "ip_pools": "ipPools",
        "is_provisioning_allowed": "isProvisioningAllowed",
        "organization_name": "organizationName",
        "service_plans": "servicePlans",
    }

    _optionals = [
        "account_name",
        "account_number",
        "carriers",
        "features",
        "ip_pools",
        "is_provisioning_allowed",
        "organization_name",
        "service_plans",
    ]

    _nullables = [
        "account_number",
    ]

    def __init__(
        self,
        account_name=APIHelper.SKIP,
        account_number=APIHelper.SKIP,
        carriers=APIHelper.SKIP,
        features=APIHelper.SKIP,
        ip_pools=APIHelper.SKIP,
        is_provisioning_allowed=APIHelper.SKIP,
        organization_name=APIHelper.SKIP,
        service_plans=APIHelper.SKIP):
        """Initialize a GetAccountInformationResponseforplanner instance."""
        # Initialize members of the class
        if account_name is not APIHelper.SKIP:
            self.account_name = account_name
        if account_number is not APIHelper.SKIP:
            self.account_number = account_number
        if carriers is not APIHelper.SKIP:
            self.carriers = carriers
        if features is not APIHelper.SKIP:
            self.features = features
        if ip_pools is not APIHelper.SKIP:
            self.ip_pools = ip_pools
        if is_provisioning_allowed is not APIHelper.SKIP:
            self.is_provisioning_allowed = is_provisioning_allowed
        if organization_name is not APIHelper.SKIP:
            self.organization_name = organization_name
        if service_plans is not APIHelper.SKIP:
            self.service_plans = service_plans

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_name =\
            dictionary.get("accountName")\
            if dictionary.get("accountName")\
                else APIHelper.SKIP
        account_number =\
            dictionary.get("accountNumber")\
            if "accountNumber" in dictionary.keys()\
                else APIHelper.SKIP
        carriers =\
            dictionary.get("carriers")\
            if dictionary.get("carriers")\
                else APIHelper.SKIP
        features =\
            dictionary.get("features")\
            if dictionary.get("features")\
                else APIHelper.SKIP
        ip_pools = None
        if dictionary.get("ipPools") is not None:
            ip_pools = [
                IPPoolforplanner.from_dictionary(x)
                    for x in dictionary.get("ipPools")
            ]
        else:
            ip_pools = APIHelper.SKIP
        is_provisioning_allowed =\
            dictionary.get("isProvisioningAllowed")\
            if "isProvisioningAllowed" in dictionary.keys()\
                else APIHelper.SKIP
        organization_name =\
            dictionary.get("organizationName")\
            if dictionary.get("organizationName")\
                else APIHelper.SKIP
        service_plans = None
        if dictionary.get("servicePlans") is not None:
            service_plans = [
                ServicePlanResponseforplanner.from_dictionary(x)
                    for x in dictionary.get("servicePlans")
            ]
        else:
            service_plans = APIHelper.SKIP

        # Return an object of this model
        return cls(account_name,
                   account_number,
                   carriers,
                   features,
                   ip_pools,
                   is_provisioning_allowed,
                   organization_name,
                   service_plans)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_name=(
            self.account_name
            if hasattr(self, "account_name")
            else None
        )
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _carriers=(
            self.carriers
            if hasattr(self, "carriers")
            else None
        )
        _features=(
            self.features
            if hasattr(self, "features")
            else None
        )
        _ip_pools=(
            self.ip_pools
            if hasattr(self, "ip_pools")
            else None
        )
        _is_provisioning_allowed=(
            self.is_provisioning_allowed
            if hasattr(self, "is_provisioning_allowed")
            else None
        )
        _organization_name=(
            self.organization_name
            if hasattr(self, "organization_name")
            else None
        )
        _service_plans=(
            self.service_plans
            if hasattr(self, "service_plans")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_name={_account_name!r}, "
            f"account_number={_account_number!r}, "
            f"carriers={_carriers!r}, "
            f"features={_features!r}, "
            f"ip_pools={_ip_pools!r}, "
            f"is_provisioning_allowed={_is_provisioning_allowed!r}, "
            f"organization_name={_organization_name!r}, "
            f"service_plans={_service_plans!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_name=(
            self.account_name
            if hasattr(self, "account_name")
            else None
        )
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _carriers=(
            self.carriers
            if hasattr(self, "carriers")
            else None
        )
        _features=(
            self.features
            if hasattr(self, "features")
            else None
        )
        _ip_pools=(
            self.ip_pools
            if hasattr(self, "ip_pools")
            else None
        )
        _is_provisioning_allowed=(
            self.is_provisioning_allowed
            if hasattr(self, "is_provisioning_allowed")
            else None
        )
        _organization_name=(
            self.organization_name
            if hasattr(self, "organization_name")
            else None
        )
        _service_plans=(
            self.service_plans
            if hasattr(self, "service_plans")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_name={_account_name!s}, "
            f"account_number={_account_number!s}, "
            f"carriers={_carriers!s}, "
            f"features={_features!s}, "
            f"ip_pools={_ip_pools!s}, "
            f"is_provisioning_allowed={_is_provisioning_allowed!s}, "
            f"organization_name={_organization_name!s}, "
            f"service_plans={_service_plans!s}, "
            f")"
        )
