"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.device_status_itemforplanner import (
    DeviceStatusItemforplanner,
)


class GetDeviceStatusesResponseforplanner(object):
    """Implementation of the 'GetDeviceStatusesResponseforplanner' model.

    Attributes:
        account_number (str): The numeric name of the account, including leading
            zeros.
        request_id (str): The model property of type str.
        device_status_list (List[DeviceStatusItemforplanner]): The model property of
            type List[DeviceStatusItemforplanner].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_number": "accountNumber",
        "request_id": "requestId",
        "device_status_list": "deviceStatusList",
    }

    _optionals = [
        "account_number",
        "request_id",
        "device_status_list",
    ]

    _nullables = [
        "account_number",
        "request_id",
        "device_status_list",
    ]

    def __init__(
        self,
        account_number=APIHelper.SKIP,
        request_id=APIHelper.SKIP,
        device_status_list=APIHelper.SKIP):
        """Initialize a GetDeviceStatusesResponseforplanner instance."""
        # Initialize members of the class
        if account_number is not APIHelper.SKIP:
            self.account_number = account_number
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id
        if device_status_list is not APIHelper.SKIP:
            self.device_status_list = device_status_list

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_number =\
            dictionary.get("accountNumber")\
            if "accountNumber" in dictionary.keys()\
                else APIHelper.SKIP
        request_id =\
            dictionary.get("requestId")\
            if "requestId" in dictionary.keys()\
                else APIHelper.SKIP
        if "deviceStatusList" in dictionary.keys():
            device_status_list = [
                DeviceStatusItemforplanner.from_dictionary(x)
                for x in dictionary.get("deviceStatusList")
            ] if dictionary.get("deviceStatusList") else None
        else:
            device_status_list = APIHelper.SKIP

        # Return an object of this model
        return cls(account_number,
                   request_id,
                   device_status_list)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _device_status_list=(
            self.device_status_list
            if hasattr(self, "device_status_list")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!r}, "
            f"request_id={_request_id!r}, "
            f"device_status_list={_device_status_list!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _device_status_list=(
            self.device_status_list
            if hasattr(self, "device_status_list")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!s}, "
            f"request_id={_request_id!s}, "
            f"device_status_list={_device_status_list!s}, "
            f")"
        )
