"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.device_listforplanner import (
    DeviceListforplanner,
)


class GetDeviceStatusesRequestforplanner(object):
    """Implementation of the 'GetDeviceStatusesRequestforplanner' model.

    Attributes:
        account_number (str): The numeric name of the account, including leading
            zeros.
        request_id (str): The unique ID of a request. This is a UUID value.
        devices (List[DeviceListforplanner]): The model property of type
            List[DeviceListforplanner].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_number": "accountNumber",
        "request_id": "requestId",
        "devices": "devices",
    }

    _optionals = [
        "account_number",
        "request_id",
        "devices",
    ]

    _nullables = [
        "account_number",
        "request_id",
        "devices",
    ]

    def __init__(
        self,
        account_number=APIHelper.SKIP,
        request_id=APIHelper.SKIP,
        devices=APIHelper.SKIP):
        """Initialize a GetDeviceStatusesRequestforplanner instance."""
        # Initialize members of the class
        if account_number is not APIHelper.SKIP:
            self.account_number = account_number
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id
        if devices is not APIHelper.SKIP:
            self.devices = devices

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_number =\
            dictionary.get("accountNumber")\
            if "accountNumber" in dictionary.keys()\
                else APIHelper.SKIP
        request_id =\
            dictionary.get("requestId")\
            if "requestId" in dictionary.keys()\
                else APIHelper.SKIP
        if "devices" in dictionary.keys():
            devices = [
                DeviceListforplanner.from_dictionary(x)
                for x in dictionary.get("devices")
            ] if dictionary.get("devices") else None
        else:
            devices = APIHelper.SKIP

        # Return an object of this model
        return cls(account_number,
                   request_id,
                   devices)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _devices=(
            self.devices
            if hasattr(self, "devices")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!r}, "
            f"request_id={_request_id!r}, "
            f"devices={_devices!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_number=(
            self.account_number
            if hasattr(self, "account_number")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _devices=(
            self.devices
            if hasattr(self, "devices")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_number={_account_number!s}, "
            f"request_id={_request_id!s}, "
            f"devices={_devices!s}, "
            f")"
        )
