"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class GetPWNPerformanceConsentResponse(object):
    """Implementation of the 'GetPWNPerformanceConsentResponse' model.

    PWN Performance Consent Response

    Attributes:
        consent (str): PWN Performance Consent Response.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "consent": "consent",
    }

    _optionals = [
        "consent",
    ]

    def __init__(
        self,
        consent=APIHelper.SKIP):
        """Initialize a GetPWNPerformanceConsentResponse instance."""
        # Initialize members of the class
        if consent is not APIHelper.SKIP:
            self.consent = consent

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        consent =\
            dictionary.get("consent")\
            if dictionary.get("consent")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(consent)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _consent=(
            self.consent
            if hasattr(self, "consent")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"consent={_consent!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _consent=(
            self.consent
            if hasattr(self, "consent")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"consent={_consent!s}, "
            f")"
        )
