"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.message_id_enum import MessageIdEnum
from verizon.models.protocol_version_enum import (
    ProtocolVersionEnum,
)


class Header(object):
    """Implementation of the 'Header' model.

    The header of the DENM PDU.

    Attributes:
        protocol_version (ProtocolVersionEnum): The protocol version of the DENM.
        message_id (MessageIdEnum): The type of ITIS message (typically 1 for DENM).
        station_id (int): The station identifier of the ITS-S.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "protocol_version": "protocolVersion",
        "message_id": "messageId",
        "station_id": "stationId",
    }

    def __init__(
        self,
        protocol_version=None,
        message_id=None,
        station_id=None):
        """Initialize a Header instance."""
        # Initialize members of the class
        self.protocol_version = protocol_version
        self.message_id = message_id
        self.station_id = station_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        protocol_version =\
            dictionary.get("protocolVersion")\
            if dictionary.get("protocolVersion")\
                else None
        message_id =\
            dictionary.get("messageId")\
            if dictionary.get("messageId")\
                else None
        station_id =\
            dictionary.get("stationId")\
            if dictionary.get("stationId")\
                else None

        # Return an object of this model
        return cls(protocol_version,
                   message_id,
                   station_id)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.protocol_version,
                    type_callable=lambda value:
                        ProtocolVersionEnum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.message_id,
                    type_callable=lambda value:
                        MessageIdEnum.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.station_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("protocolVersion"),
                type_callable=lambda value:
                    ProtocolVersionEnum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("messageId"),
                type_callable=lambda value:
                    MessageIdEnum.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("stationId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _protocol_version=self.protocol_version
        _message_id=self.message_id
        _station_id=self.station_id
        return (
            f"{self.__class__.__name__}("
            f"protocol_version={_protocol_version!r}, "
            f"message_id={_message_id!r}, "
            f"station_id={_station_id!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _protocol_version=self.protocol_version
        _message_id=self.message_id
        _station_id=self.station_id
        return (
            f"{self.__class__.__name__}("
            f"protocol_version={_protocol_version!s}, "
            f"message_id={_message_id!s}, "
            f"station_id={_station_id!s}, "
            f")"
        )
