"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.hpl_account_device_list import (
    HplAccountDeviceList,
)
from verizon.models.hpl_custom_fields import (
    HplCustomFields,
)


class HplAddDevicesRequest(object):
    """Implementation of the 'hpl.AddDevicesRequest' model.

    Request to add the devices.

    Attributes:
        state (str): The initial service state for the devices. The only valid state
            is "Preactive."
        devices_to_add (List[HplAccountDeviceList]): The devices that you want to add.
        account_name (str): The numeric name of the account and must include leading
            zeroes.
        custom_fields (List[HplCustomFields]): The names and values for any custom
            fields that you want set for the devices as they are added to the account.
        group_name (str): The name of a device group to add the devices to. They are
            added to the default device group if you don't include this parameter.
        sku_number (str): The Stock Keeping Unit (SKU) number of a 4G device type
            with an embedded SIM.
        smsr_oid (str): The Subscription Manager Secure Router Object ID, used for
            remote SIM provisioning. SMSR securely routes the download and management
            of eSIM profiles.
        number_of_virtual_imei (int): numberOfVirtualImei.
        upload_type (str): uploadType.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "state": "state",
        "devices_to_add": "devicesToAdd",
        "account_name": "accountName",
        "custom_fields": "customFields",
        "group_name": "groupName",
        "sku_number": "skuNumber",
        "smsr_oid": "smsrOid",
        "number_of_virtual_imei": "numberOfVirtualImei",
        "upload_type": "uploadType",
    }

    _optionals = [
        "state",
        "devices_to_add",
        "account_name",
        "custom_fields",
        "group_name",
        "sku_number",
        "smsr_oid",
        "number_of_virtual_imei",
        "upload_type",
    ]

    def __init__(
        self,
        state=APIHelper.SKIP,
        devices_to_add=APIHelper.SKIP,
        account_name=APIHelper.SKIP,
        custom_fields=APIHelper.SKIP,
        group_name=APIHelper.SKIP,
        sku_number=APIHelper.SKIP,
        smsr_oid=APIHelper.SKIP,
        number_of_virtual_imei=APIHelper.SKIP,
        upload_type=APIHelper.SKIP):
        """Initialize a HplAddDevicesRequest instance."""
        # Initialize members of the class
        if state is not APIHelper.SKIP:
            self.state = state
        if devices_to_add is not APIHelper.SKIP:
            self.devices_to_add = devices_to_add
        if account_name is not APIHelper.SKIP:
            self.account_name = account_name
        if custom_fields is not APIHelper.SKIP:
            self.custom_fields = custom_fields
        if group_name is not APIHelper.SKIP:
            self.group_name = group_name
        if sku_number is not APIHelper.SKIP:
            self.sku_number = sku_number
        if smsr_oid is not APIHelper.SKIP:
            self.smsr_oid = smsr_oid
        if number_of_virtual_imei is not APIHelper.SKIP:
            self.number_of_virtual_imei = number_of_virtual_imei
        if upload_type is not APIHelper.SKIP:
            self.upload_type = upload_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else APIHelper.SKIP
        devices_to_add = None
        if dictionary.get("devicesToAdd") is not None:
            devices_to_add = [
                HplAccountDeviceList.from_dictionary(x)
                    for x in dictionary.get("devicesToAdd")
            ]
        else:
            devices_to_add = APIHelper.SKIP
        account_name =\
            dictionary.get("accountName")\
            if dictionary.get("accountName")\
                else APIHelper.SKIP
        custom_fields = None
        if dictionary.get("customFields") is not None:
            custom_fields = [
                HplCustomFields.from_dictionary(x)
                    for x in dictionary.get("customFields")
            ]
        else:
            custom_fields = APIHelper.SKIP
        group_name =\
            dictionary.get("groupName")\
            if dictionary.get("groupName")\
                else APIHelper.SKIP
        sku_number =\
            dictionary.get("skuNumber")\
            if dictionary.get("skuNumber")\
                else APIHelper.SKIP
        smsr_oid =\
            dictionary.get("smsrOid")\
            if dictionary.get("smsrOid")\
                else APIHelper.SKIP
        number_of_virtual_imei =\
            dictionary.get("numberOfVirtualImei")\
            if dictionary.get("numberOfVirtualImei")\
                else APIHelper.SKIP
        upload_type =\
            dictionary.get("uploadType")\
            if dictionary.get("uploadType")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(state,
                   devices_to_add,
                   account_name,
                   custom_fields,
                   group_name,
                   sku_number,
                   smsr_oid,
                   number_of_virtual_imei,
                   upload_type)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _devices_to_add=(
            self.devices_to_add
            if hasattr(self, "devices_to_add")
            else None
        )
        _account_name=(
            self.account_name
            if hasattr(self, "account_name")
            else None
        )
        _custom_fields=(
            self.custom_fields
            if hasattr(self, "custom_fields")
            else None
        )
        _group_name=(
            self.group_name
            if hasattr(self, "group_name")
            else None
        )
        _sku_number=(
            self.sku_number
            if hasattr(self, "sku_number")
            else None
        )
        _smsr_oid=(
            self.smsr_oid
            if hasattr(self, "smsr_oid")
            else None
        )
        _number_of_virtual_imei=(
            self.number_of_virtual_imei
            if hasattr(self, "number_of_virtual_imei")
            else None
        )
        _upload_type=(
            self.upload_type
            if hasattr(self, "upload_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"state={_state!r}, "
            f"devices_to_add={_devices_to_add!r}, "
            f"account_name={_account_name!r}, "
            f"custom_fields={_custom_fields!r}, "
            f"group_name={_group_name!r}, "
            f"sku_number={_sku_number!r}, "
            f"smsr_oid={_smsr_oid!r}, "
            f"number_of_virtual_imei={_number_of_virtual_imei!r}, "
            f"upload_type={_upload_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _devices_to_add=(
            self.devices_to_add
            if hasattr(self, "devices_to_add")
            else None
        )
        _account_name=(
            self.account_name
            if hasattr(self, "account_name")
            else None
        )
        _custom_fields=(
            self.custom_fields
            if hasattr(self, "custom_fields")
            else None
        )
        _group_name=(
            self.group_name
            if hasattr(self, "group_name")
            else None
        )
        _sku_number=(
            self.sku_number
            if hasattr(self, "sku_number")
            else None
        )
        _smsr_oid=(
            self.smsr_oid
            if hasattr(self, "smsr_oid")
            else None
        )
        _number_of_virtual_imei=(
            self.number_of_virtual_imei
            if hasattr(self, "number_of_virtual_imei")
            else None
        )
        _upload_type=(
            self.upload_type
            if hasattr(self, "upload_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"state={_state!s}, "
            f"devices_to_add={_devices_to_add!s}, "
            f"account_name={_account_name!s}, "
            f"custom_fields={_custom_fields!s}, "
            f"group_name={_group_name!s}, "
            f"sku_number={_sku_number!s}, "
            f"smsr_oid={_smsr_oid!s}, "
            f"number_of_virtual_imei={_number_of_virtual_imei!s}, "
            f"upload_type={_upload_type!s}, "
            f")"
        )
