"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class ImpassabilityCauseCode(object):
    """Implementation of the 'ImpassabilityCauseCode' model.

    Cause code wrapper for impassability events.

    Attributes:
        impassability_5 (int): The value shall be set to: - 0 `unavailable`
            - in case further detailed information about the unmanaged road blockage
            is unavailable, - 1 `flooding          `       - in case the road is
            affected by flooding, - 2 `dangerOfAvalanches`       - in case the road
            is at risk of being affected or blocked by avalanches, - 3
            `blastingOfAvalanches`     - in case there is an active blasting of
            avalanches on or near the road, - 4 `landslips`                - in case
            the road is affected by landslips, - 5 `chemicalSpillage`         - in
            case the road is affected by chemical spillage, - 6 `winterClosure`
            - in case the road is impassable due to a winter closure. - 7 `sinkhole`
            - in case the road is impassable due to large holes in the road surface.
            - 8 `earthquakeDamage`         - in case the road is obstructed or
            partially obstructed because of damage caused by an earthquake. - 9
            `fallenTrees`              - in case the road is obstructed or partially
            obstructed by one or more fallen trees. - 10 `rockfalls`               -
            in case the road is obstructed or partially obstructed due to fallen
            rocks. - 11 `sewerOverflow`           - in case the road is obstructed or
            partially obstructed by overflows from one or more sewers. - 12
            `stormDamage`             - in case the road is obstructed or partially
            obstructed by debris caused by strong winds. - 13 `subsidence`
            - in case the road surface has sunken or collapsed in places. - 14
            `burstPipe`               - in case the road surface has sunken or
            collapsed in places due to burst pipes. - 15 `burstWaterMain`          -
            in case the road is obstructed due to local flooding and/or subsidence. -
            16 `fallenPowerCables`       - in case the road is obstructed or partly
            obstructed by one or more fallen power cables. - 17 `snowDrifts`
            - in case the road is obstructed or partially obstructed by snow drifting
            in progress or patches of deep snow due to earlier drifting. - 15-255
            - are reserved for future usage.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "impassability_5": "impassability5",
    }

    def __init__(
        self,
        impassability_5=None):
        """Initialize a ImpassabilityCauseCode instance."""
        # Initialize members of the class
        self.impassability_5 = impassability_5

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        impassability_5 =\
            dictionary.get("impassability5")\
            if dictionary.get("impassability5")\
                else None

        # Return an object of this model
        return cls(impassability_5)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.impassability_5,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("impassability5"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _impassability_5=self.impassability_5
        return (
            f"{self.__class__.__name__}("
            f"impassability_5={_impassability_5!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _impassability_5=self.impassability_5
        return (
            f"{self.__class__.__name__}("
            f"impassability_5={_impassability_5!s}, "
            f")"
        )
