"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class IPPoolforplanner(object):
    """Implementation of the 'IPPoolforplanner' model.

    Attributes:
        is_default_pool (bool): The model property of type bool.
        pool_name (str): The model property of type str.
        pool_type (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_default_pool": "isDefaultPool",
        "pool_name": "poolName",
        "pool_type": "poolType",
    }

    _optionals = [
        "is_default_pool",
        "pool_name",
        "pool_type",
    ]

    def __init__(
        self,
        is_default_pool=APIHelper.SKIP,
        pool_name=APIHelper.SKIP,
        pool_type=APIHelper.SKIP):
        """Initialize a IPPoolforplanner instance."""
        # Initialize members of the class
        if is_default_pool is not APIHelper.SKIP:
            self.is_default_pool = is_default_pool
        if pool_name is not APIHelper.SKIP:
            self.pool_name = pool_name
        if pool_type is not APIHelper.SKIP:
            self.pool_type = pool_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        is_default_pool =\
            dictionary.get("isDefaultPool")\
            if "isDefaultPool" in dictionary.keys()\
                else APIHelper.SKIP
        pool_name =\
            dictionary.get("poolName")\
            if dictionary.get("poolName")\
                else APIHelper.SKIP
        pool_type =\
            dictionary.get("poolType")\
            if dictionary.get("poolType")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(is_default_pool,
                   pool_name,
                   pool_type)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _is_default_pool=(
            self.is_default_pool
            if hasattr(self, "is_default_pool")
            else None
        )
        _pool_name=(
            self.pool_name
            if hasattr(self, "pool_name")
            else None
        )
        _pool_type=(
            self.pool_type
            if hasattr(self, "pool_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"is_default_pool={_is_default_pool!r}, "
            f"pool_name={_pool_name!r}, "
            f"pool_type={_pool_type!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _is_default_pool=(
            self.is_default_pool
            if hasattr(self, "is_default_pool")
            else None
        )
        _pool_name=(
            self.pool_name
            if hasattr(self, "pool_name")
            else None
        )
        _pool_type=(
            self.pool_type
            if hasattr(self, "pool_type")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"is_default_pool={_is_default_pool!s}, "
            f"pool_name={_pool_name!s}, "
            f"pool_type={_pool_type!s}, "
            f")"
        )
