"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.itis_item_content import (
    ITISItemContent,
)


class ITISItemWrapper(object):
    """Implementation of the 'ITISItemWrapper' model.

    A wrapper carrying an ITIS code item.

    Attributes:
        item (ITISItemContent): An item object wrapping an ITIS code value.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "item": "item",
    }

    def __init__(
        self,
        item=None):
        """Initialize a ITISItemWrapper instance."""
        # Initialize members of the class
        self.item = item

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        item =\
            ITISItemContent.from_dictionary(
                dictionary.get("item"))\
                if dictionary.get("item") else None

        # Return an object of this model
        return cls(item)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.item,
                    type_callable=lambda value:
                        ITISItemContent.validate(value),
                    is_model_dict=True)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("item"),
                type_callable=lambda value:
                    ITISItemContent.validate(value),
                is_model_dict=True)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _item=self.item
        return (
            f"{self.__class__.__name__}("
            f"item={_item!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _item=self.item
        return (
            f"{self.__class__.__name__}("
            f"item={_item!s}, "
            f")"
        )
