"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.address_item import AddressItem


class Locations(object):
    """Implementation of the 'Locations' model.

    Location details.

    Attributes:
        address_list (List[AddressItem]): The model property of type
            List[AddressItem].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "address_list": "addressList",
    }

    _optionals = [
        "address_list",
    ]

    def __init__(
        self,
        address_list=APIHelper.SKIP):
        """Initialize a Locations instance."""
        # Initialize members of the class
        if address_list is not APIHelper.SKIP:
            self.address_list = address_list

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        address_list = None
        if dictionary.get("addressList") is not None:
            address_list = [
                AddressItem.from_dictionary(x)
                    for x in dictionary.get("addressList")
            ]
        else:
            address_list = APIHelper.SKIP

        # Return an object of this model
        return cls(address_list)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _address_list=(
            self.address_list
            if hasattr(self, "address_list")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"address_list={_address_list!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _address_list=(
            self.address_list
            if hasattr(self, "address_list")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"address_list={_address_list!s}, "
            f")"
        )
