"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class M5gBiCarrierInformation(object):
    """Implementation of the '5gbiCarrierInformation' model.

    Attributes:
        carrier_name (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "carrier_name": "carrierName",
    }

    _optionals = [
        "carrier_name",
    ]

    def __init__(
        self,
        carrier_name=APIHelper.SKIP):
        """Initialize a M5gBiCarrierInformation instance."""
        # Initialize members of the class
        if carrier_name is not APIHelper.SKIP:
            self.carrier_name = carrier_name

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        carrier_name =\
            dictionary.get("carrierName")\
            if dictionary.get("carrierName")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(carrier_name)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _carrier_name=(
            self.carrier_name
            if hasattr(self, "carrier_name")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"carrier_name={_carrier_name!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _carrier_name=(
            self.carrier_name
            if hasattr(self, "carrier_name")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"carrier_name={_carrier_name!s}, "
            f")"
        )
