"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.m_5g_biprimary_placeofuse import (
    M5gBiprimaryPlaceofuse,
)


class M5gBiaddressAndcustomerinfo(object):
    """Implementation of the '5gbiaddressAndcustomerinfo' model.

    Attributes:
        primary_placeofuse (M5gBiprimaryPlaceofuse): The model property of type
            M5gBiprimaryPlaceofuse.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "primary_placeofuse": "primaryPlaceofuse",
    }

    _optionals = [
        "primary_placeofuse",
    ]

    def __init__(
        self,
        primary_placeofuse=APIHelper.SKIP):
        """Initialize a M5gBiaddressAndcustomerinfo instance."""
        # Initialize members of the class
        if primary_placeofuse is not APIHelper.SKIP:
            self.primary_placeofuse = primary_placeofuse

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        primary_placeofuse =\
            M5gBiprimaryPlaceofuse.from_dictionary(
                dictionary.get("primaryPlaceofuse"))\
                if "primaryPlaceofuse" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(primary_placeofuse)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _primary_placeofuse=(
            self.primary_placeofuse
            if hasattr(self, "primary_placeofuse")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"primary_placeofuse={_primary_placeofuse!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _primary_placeofuse=(
            self.primary_placeofuse
            if hasattr(self, "primary_placeofuse")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"primary_placeofuse={_primary_placeofuse!s}, "
            f")"
        )
