"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class NetworkTypeEnum(object):
    """Implementation of the 'NetworkType' enum.

    The type of the device's network connection at the time of the request. If the
    device is on the Verizon cellular network it should use the "VZ" value otherwise
    the "non-VZ" value.
    Devices on the Verizon network can directly access the ETX Message Exchange on
    the MEC (Mobile Edge Compute server)

    Attributes:
        VZ: The enum member of type str.
        NONVZ: The enum member of type str.

    """

    VZ = "VZ"

    NONVZ = "non-VZ"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
