"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class NodeLLmD64b(object):
    """Implementation of the 'Node-LLmD-64b' model.

    A 64-bit node type with lat-long values expressed in standard SAE 1/10th of a
    microdegree.

    Attributes:
        lon (int): The geographic longitude of an object, expressed in 1/10th integer
            microdegrees, as a 32-bit value, and with reference to the horizontal
            datum then in use. The value 1800000001 shall be used when unavailable.
        lat (int): The geographic latitude of an object, expressed in 1/10th integer
            microdegrees, as a 31 bit value, and with reference to the horizontal
            datum then in use. The value 900000001 shall be used when unavailable.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "lon": "lon",
        "lat": "lat",
    }

    def __init__(
        self,
        lon=None,
        lat=None):
        """Initialize a NodeLLmD64b instance."""
        # Initialize members of the class
        self.lon = lon
        self.lat = lat

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        lon =\
            dictionary.get("lon")\
            if dictionary.get("lon")\
                else None
        lat =\
            dictionary.get("lat")\
            if dictionary.get("lat")\
                else None

        # Return an object of this model
        return cls(lon,
                   lat)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.lon,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.lat,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("lon"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("lat"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _lon=self.lon
        _lat=self.lat
        return (
            f"{self.__class__.__name__}("
            f"lon={_lon!r}, "
            f"lat={_lat!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _lon=self.lon
        _lat=self.lat
        return (
            f"{self.__class__.__name__}("
            f"lon={_lon!s}, "
            f"lat={_lat!s}, "
            f")"
        )
