"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class Notificationarray(object):
    """Implementation of the 'notificationarray' model.

    Attributes:
        notification_type (str): The model property of type str.
        callback (bool): The model property of type bool.
        email_notification (bool): The model property of type bool.
        notification_group_name (str): The model property of type str.
        notification_frequency_factor (int): The model property of type int.
        notification_frequency_interval (str): The model property of type str.
        external_email_recipients (str): The model property of type str.
        sms_notification (bool): The model property of type bool.
        sms_numbers (List[Cellphonenumber] | None): The model property of type
            List[Cellphonenumber] | None.
        reminder (bool): The model property of type bool.
        severity (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "notification_type": "notificationType",
        "callback": "callback",
        "email_notification": "emailNotification",
        "notification_group_name": "notificationGroupName",
        "notification_frequency_factor": "notificationFrequencyFactor",
        "notification_frequency_interval": "notificationFrequencyInterval",
        "external_email_recipients": "externalEmailRecipients",
        "sms_notification": "smsNotification",
        "sms_numbers": "smsNumbers",
        "reminder": "reminder",
        "severity": "severity",
    }

    _optionals = [
        "notification_type",
        "callback",
        "email_notification",
        "notification_group_name",
        "notification_frequency_factor",
        "notification_frequency_interval",
        "external_email_recipients",
        "sms_notification",
        "sms_numbers",
        "reminder",
        "severity",
    ]

    def __init__(
        self,
        notification_type=APIHelper.SKIP,
        callback=APIHelper.SKIP,
        email_notification=APIHelper.SKIP,
        notification_group_name=APIHelper.SKIP,
        notification_frequency_factor=APIHelper.SKIP,
        notification_frequency_interval=APIHelper.SKIP,
        external_email_recipients=APIHelper.SKIP,
        sms_notification=APIHelper.SKIP,
        sms_numbers=APIHelper.SKIP,
        reminder=APIHelper.SKIP,
        severity=APIHelper.SKIP):
        """Initialize a Notificationarray instance."""
        # Initialize members of the class
        if notification_type is not APIHelper.SKIP:
            self.notification_type = notification_type
        if callback is not APIHelper.SKIP:
            self.callback = callback
        if email_notification is not APIHelper.SKIP:
            self.email_notification = email_notification
        if notification_group_name is not APIHelper.SKIP:
            self.notification_group_name = notification_group_name
        if notification_frequency_factor is not APIHelper.SKIP:
            self.notification_frequency_factor = notification_frequency_factor
        if notification_frequency_interval is not APIHelper.SKIP:
            self.notification_frequency_interval = notification_frequency_interval
        if external_email_recipients is not APIHelper.SKIP:
            self.external_email_recipients = external_email_recipients
        if sms_notification is not APIHelper.SKIP:
            self.sms_notification = sms_notification
        if sms_numbers is not APIHelper.SKIP:
            self.sms_numbers = sms_numbers
        if reminder is not APIHelper.SKIP:
            self.reminder = reminder
        if severity is not APIHelper.SKIP:
            self.severity = severity

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        notification_type =\
            dictionary.get("notificationType")\
            if dictionary.get("notificationType")\
                else APIHelper.SKIP
        callback =\
            dictionary.get("callback")\
            if "callback" in dictionary.keys()\
                else APIHelper.SKIP
        email_notification =\
            dictionary.get("emailNotification")\
            if "emailNotification" in dictionary.keys()\
                else APIHelper.SKIP
        notification_group_name =\
            dictionary.get("notificationGroupName")\
            if dictionary.get("notificationGroupName")\
                else APIHelper.SKIP
        notification_frequency_factor =\
            dictionary.get("notificationFrequencyFactor")\
            if dictionary.get("notificationFrequencyFactor")\
                else APIHelper.SKIP
        notification_frequency_interval =\
            dictionary.get("notificationFrequencyInterval")\
            if dictionary.get("notificationFrequencyInterval")\
                else APIHelper.SKIP
        external_email_recipients =\
            dictionary.get("externalEmailRecipients")\
            if dictionary.get("externalEmailRecipients")\
                else APIHelper.SKIP
        sms_notification =\
            dictionary.get("smsNotification")\
            if "smsNotification" in dictionary.keys()\
                else APIHelper.SKIP
        sms_numbers = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("NotificationarraySmsNumbers"),
            dictionary.get("smsNumbers"),
            False)\
            if dictionary.get("smsNumbers") is not None\
            else APIHelper.SKIP
        reminder =\
            dictionary.get("reminder")\
            if "reminder" in dictionary.keys()\
                else APIHelper.SKIP
        severity =\
            dictionary.get("severity")\
            if dictionary.get("severity")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(notification_type,
                   callback,
                   email_notification,
                   notification_group_name,
                   notification_frequency_factor,
                   notification_frequency_interval,
                   external_email_recipients,
                   sms_notification,
                   sms_numbers,
                   reminder,
                   severity)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _notification_type=(
            self.notification_type
            if hasattr(self, "notification_type")
            else None
        )
        _callback=(
            self.callback
            if hasattr(self, "callback")
            else None
        )
        _email_notification=(
            self.email_notification
            if hasattr(self, "email_notification")
            else None
        )
        _notification_group_name=(
            self.notification_group_name
            if hasattr(self, "notification_group_name")
            else None
        )
        _notification_frequency_factor=(
            self.notification_frequency_factor
            if hasattr(self, "notification_frequency_factor")
            else None
        )
        _notification_frequency_interval=(
            self.notification_frequency_interval
            if hasattr(self, "notification_frequency_interval")
            else None
        )
        _external_email_recipients=(
            self.external_email_recipients
            if hasattr(self, "external_email_recipients")
            else None
        )
        _sms_notification=(
            self.sms_notification
            if hasattr(self, "sms_notification")
            else None
        )
        _sms_numbers=(
            self.sms_numbers
            if hasattr(self, "sms_numbers")
            else None
        )
        _reminder=(
            self.reminder
            if hasattr(self, "reminder")
            else None
        )
        _severity=(
            self.severity
            if hasattr(self, "severity")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"notification_type={_notification_type!r}, "
            f"callback={_callback!r}, "
            f"email_notification={_email_notification!r}, "
            f"notification_group_name={_notification_group_name!r}, "
            f"notification_frequency_factor={_notification_frequency_factor!r}, "
            f"notification_frequency_interval={_notification_frequency_interval!r}, "
            f"external_email_recipients={_external_email_recipients!r}, "
            f"sms_notification={_sms_notification!r}, "
            f"sms_numbers={_sms_numbers!r}, "
            f"reminder={_reminder!r}, "
            f"severity={_severity!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _notification_type=(
            self.notification_type
            if hasattr(self, "notification_type")
            else None
        )
        _callback=(
            self.callback
            if hasattr(self, "callback")
            else None
        )
        _email_notification=(
            self.email_notification
            if hasattr(self, "email_notification")
            else None
        )
        _notification_group_name=(
            self.notification_group_name
            if hasattr(self, "notification_group_name")
            else None
        )
        _notification_frequency_factor=(
            self.notification_frequency_factor
            if hasattr(self, "notification_frequency_factor")
            else None
        )
        _notification_frequency_interval=(
            self.notification_frequency_interval
            if hasattr(self, "notification_frequency_interval")
            else None
        )
        _external_email_recipients=(
            self.external_email_recipients
            if hasattr(self, "external_email_recipients")
            else None
        )
        _sms_notification=(
            self.sms_notification
            if hasattr(self, "sms_notification")
            else None
        )
        _sms_numbers=(
            self.sms_numbers
            if hasattr(self, "sms_numbers")
            else None
        )
        _reminder=(
            self.reminder
            if hasattr(self, "reminder")
            else None
        )
        _severity=(
            self.severity
            if hasattr(self, "severity")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"notification_type={_notification_type!s}, "
            f"callback={_callback!s}, "
            f"email_notification={_email_notification!s}, "
            f"notification_group_name={_notification_group_name!s}, "
            f"notification_frequency_factor={_notification_frequency_factor!s}, "
            f"notification_frequency_interval={_notification_frequency_interval!s}, "
            f"external_email_recipients={_external_email_recipients!s}, "
            f"sms_notification={_sms_notification!s}, "
            f"sms_numbers={_sms_numbers!s}, "
            f"reminder={_reminder!s}, "
            f"severity={_severity!s}, "
            f")"
        )
