"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class PaginationFilter(object):
    """Implementation of the 'PaginationFilter' model.

    Pagination filter containing an opaque token for fetching the next/previous page
    of results.
    The page token is returned in the response headers (X-Next, X-Prev) and should be
    passed as-is.

    Attributes:
        page (str): Opaque pagination token for fetching the next/previous page of
            results. This is a encoded string. Do not parse or modify; pass it as
            received.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page": "Page",
    }

    def __init__(
        self,
        page=None):
        """Initialize a PaginationFilter instance."""
        # Initialize members of the class
        self.page = page

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        page =\
            dictionary.get("Page")\
            if dictionary.get("Page")\
                else None

        # Return an object of this model
        return cls(page)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.page,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("Page"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _page=self.page
        return (
            f"{self.__class__.__name__}("
            f"page={_page!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _page=self.page
        return (
            f"{self.__class__.__name__}("
            f"page={_page!s}, "
            f")"
        )
