"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.account_share_filter_criteria import (
    AccountShareFilterCriteria,
)
from verizon.models.actionobject import Actionobject
from verizon.models.change_plan_details import (
    ChangePlanDetails,
)
from verizon.models.filtercriteria_object_call import (
    FiltercriteriaObjectCall,
)
from verizon.models.pay_as_you_go_filter_criteria import (
    PayAsYouGoFilterCriteria,
)


class PricePlanTrigger2(object):
    """Implementation of the 'PricePlanTrigger2' model.

    Attributes:
        account_share (AccountShareFilterCriteria): The model property of type
            AccountShareFilterCriteria.
        condition (ConditionTypeEnum | ConditionObjectCall | None): The model
            property of type ConditionTypeEnum | ConditionObjectCall | None.
        change_plan (bool): a flag to set if the trigger changes service plans, true,
            or not, false
        change_plan_details (ChangePlanDetails): The service plan code to switch to
        pay_as_you_go (PayAsYouGoFilterCriteria): The model property of type
            PayAsYouGoFilterCriteria.
        action (Actionobject): The model property of type Actionobject.
        stand_alone (FiltercriteriaObjectCall): The model property of type
            FiltercriteriaObjectCall.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_share": "accountShare",
        "condition": "condition",
        "change_plan": "changePlan",
        "change_plan_details": "changePlanDetails",
        "pay_as_you_go": "payAsYouGo",
        "action": "action",
        "stand_alone": "standAlone",
    }

    _optionals = [
        "account_share",
        "condition",
        "change_plan",
        "change_plan_details",
        "pay_as_you_go",
        "action",
        "stand_alone",
    ]

    def __init__(
        self,
        account_share=APIHelper.SKIP,
        condition=APIHelper.SKIP,
        change_plan=APIHelper.SKIP,
        change_plan_details=APIHelper.SKIP,
        pay_as_you_go=APIHelper.SKIP,
        action=APIHelper.SKIP,
        stand_alone=APIHelper.SKIP):
        """Initialize a PricePlanTrigger2 instance."""
        # Initialize members of the class
        if account_share is not APIHelper.SKIP:
            self.account_share = account_share
        if condition is not APIHelper.SKIP:
            self.condition = condition
        if change_plan is not APIHelper.SKIP:
            self.change_plan = change_plan
        if change_plan_details is not APIHelper.SKIP:
            self.change_plan_details = change_plan_details
        if pay_as_you_go is not APIHelper.SKIP:
            self.pay_as_you_go = pay_as_you_go
        if action is not APIHelper.SKIP:
            self.action = action
        if stand_alone is not APIHelper.SKIP:
            self.stand_alone = stand_alone

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_share =\
            AccountShareFilterCriteria.from_dictionary(
                dictionary.get("accountShare"))\
                if "accountShare" in dictionary.keys()\
                else APIHelper.SKIP
        condition = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("PricePlanTrigger2Condition"),
            dictionary.get("condition"),
            False)\
            if dictionary.get("condition") is not None\
            else APIHelper.SKIP
        change_plan =\
            dictionary.get("changePlan")\
            if "changePlan" in dictionary.keys()\
                else APIHelper.SKIP
        change_plan_details =\
            ChangePlanDetails.from_dictionary(
                dictionary.get("changePlanDetails"))\
                if "changePlanDetails" in dictionary.keys()\
                else APIHelper.SKIP
        pay_as_you_go =\
            PayAsYouGoFilterCriteria.from_dictionary(
                dictionary.get("payAsYouGo"))\
                if "payAsYouGo" in dictionary.keys()\
                else APIHelper.SKIP
        action =\
            Actionobject.from_dictionary(
                dictionary.get("action"))\
                if "action" in dictionary.keys()\
                else APIHelper.SKIP
        stand_alone =\
            FiltercriteriaObjectCall.from_dictionary(
                dictionary.get("standAlone"))\
                if "standAlone" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_share,
                   condition,
                   change_plan,
                   change_plan_details,
                   pay_as_you_go,
                   action,
                   stand_alone)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _account_share=(
            self.account_share
            if hasattr(self, "account_share")
            else None
        )
        _condition=(
            self.condition
            if hasattr(self, "condition")
            else None
        )
        _change_plan=(
            self.change_plan
            if hasattr(self, "change_plan")
            else None
        )
        _change_plan_details=(
            self.change_plan_details
            if hasattr(self, "change_plan_details")
            else None
        )
        _pay_as_you_go=(
            self.pay_as_you_go
            if hasattr(self, "pay_as_you_go")
            else None
        )
        _action=(
            self.action
            if hasattr(self, "action")
            else None
        )
        _stand_alone=(
            self.stand_alone
            if hasattr(self, "stand_alone")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_share={_account_share!r}, "
            f"condition={_condition!r}, "
            f"change_plan={_change_plan!r}, "
            f"change_plan_details={_change_plan_details!r}, "
            f"pay_as_you_go={_pay_as_you_go!r}, "
            f"action={_action!r}, "
            f"stand_alone={_stand_alone!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _account_share=(
            self.account_share
            if hasattr(self, "account_share")
            else None
        )
        _condition=(
            self.condition
            if hasattr(self, "condition")
            else None
        )
        _change_plan=(
            self.change_plan
            if hasattr(self, "change_plan")
            else None
        )
        _change_plan_details=(
            self.change_plan_details
            if hasattr(self, "change_plan_details")
            else None
        )
        _pay_as_you_go=(
            self.pay_as_you_go
            if hasattr(self, "pay_as_you_go")
            else None
        )
        _action=(
            self.action
            if hasattr(self, "action")
            else None
        )
        _stand_alone=(
            self.stand_alone
            if hasattr(self, "stand_alone")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"account_share={_account_share!s}, "
            f"condition={_condition!s}, "
            f"change_plan={_change_plan!s}, "
            f"change_plan_details={_change_plan_details!s}, "
            f"pay_as_you_go={_pay_as_you_go!s}, "
            f"action={_action!s}, "
            f"stand_alone={_stand_alone!s}, "
            f")"
        )
