"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.rbs_high_precision_tilt_config import (
    RbsHighPrecisionTiltConfig,
)


class Rbstiltconfig(object):
    """Implementation of the 'rbstiltconfig' model.

    Attributes:
        rbs_high_precision_tilt_config (RbsHighPrecisionTiltConfig): The model
            property of type RbsHighPrecisionTiltConfig.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "rbs_high_precision_tilt_config": "RbsHighPrecisionTiltConfig",
    }

    _optionals = [
        "rbs_high_precision_tilt_config",
    ]

    def __init__(
        self,
        rbs_high_precision_tilt_config=APIHelper.SKIP):
        """Initialize a Rbstiltconfig instance."""
        # Initialize members of the class
        if rbs_high_precision_tilt_config is not APIHelper.SKIP:
            self.rbs_high_precision_tilt_config = rbs_high_precision_tilt_config

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        rbs_high_precision_tilt_config =\
            RbsHighPrecisionTiltConfig.from_dictionary(
                dictionary.get("RbsHighPrecisionTiltConfig"))\
                if "RbsHighPrecisionTiltConfig" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(rbs_high_precision_tilt_config)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _rbs_high_precision_tilt_config=(
            self.rbs_high_precision_tilt_config
            if hasattr(self, "rbs_high_precision_tilt_config")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"rbs_high_precision_tilt_config={_rbs_high_precision_tilt_config!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _rbs_high_precision_tilt_config=(
            self.rbs_high_precision_tilt_config
            if hasattr(self, "rbs_high_precision_tilt_config")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"rbs_high_precision_tilt_config={_rbs_high_precision_tilt_config!s}, "
            f")"
        )
