"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class ResourceRule(object):
    """Implementation of the 'resource.Rule' model.

    Attributes:
        accountclientid (str): Not used in this release, future functionality
        billingaccountid (str): The billing account ID. This is the same value as the
            Account ID
        createdon (datetime): Timestamp of the record
        description (str): a short description
        deviceid (str): This is a UUID value of the device created when the device is
            onboarded
        disabled (bool): The model property of type bool.
        foreignid (str): UUID of the ECPD account the user belongs to
        id (str): UUID of the user record, assigned at creation
        lastupdated (datetime): Timestamp of the record
        name (str): User defined name of the record
        rulechain (Any): The model property of type Any.
        rulesyntax (str): The syntax of the rule and supports camel and json style
            syntaxes
        version (str): The resource version
        versionid (str): The UUID of the resource version

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "createdon": "createdon",
        "foreignid": "foreignid",
        "lastupdated": "lastupdated",
        "rulechain": "rulechain",
        "versionid": "versionid",
        "accountclientid": "accountclientid",
        "billingaccountid": "billingaccountid",
        "description": "description",
        "deviceid": "deviceid",
        "disabled": "disabled",
        "id": "id",
        "name": "name",
        "rulesyntax": "rulesyntax",
        "version": "version",
    }

    _optionals = [
        "accountclientid",
        "billingaccountid",
        "description",
        "deviceid",
        "disabled",
        "id",
        "name",
        "rulesyntax",
        "version",
    ]

    def __init__(
        self,
        createdon=None,
        foreignid=None,
        lastupdated=None,
        rulechain=None,
        versionid=None,
        accountclientid=APIHelper.SKIP,
        billingaccountid=APIHelper.SKIP,
        description=APIHelper.SKIP,
        deviceid=APIHelper.SKIP,
        disabled=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        rulesyntax=APIHelper.SKIP,
        version=APIHelper.SKIP):
        """Initialize a ResourceRule instance."""
        # Initialize members of the class
        if accountclientid is not APIHelper.SKIP:
            self.accountclientid = accountclientid
        if billingaccountid is not APIHelper.SKIP:
            self.billingaccountid = billingaccountid
        self.createdon =\
             APIHelper.apply_datetime_converter(
            createdon, APIHelper.RFC3339DateTime)\
             if createdon else None
        if description is not APIHelper.SKIP:
            self.description = description
        if deviceid is not APIHelper.SKIP:
            self.deviceid = deviceid
        if disabled is not APIHelper.SKIP:
            self.disabled = disabled
        self.foreignid = foreignid
        if id is not APIHelper.SKIP:
            self.id = id
        self.lastupdated =\
             APIHelper.apply_datetime_converter(
            lastupdated, APIHelper.RFC3339DateTime)\
             if lastupdated else None
        if name is not APIHelper.SKIP:
            self.name = name
        self.rulechain = rulechain
        if rulesyntax is not APIHelper.SKIP:
            self.rulesyntax = rulesyntax
        if version is not APIHelper.SKIP:
            self.version = version
        self.versionid = versionid

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        createdon = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("createdon")).datetime\
            if dictionary.get("createdon") else None
        foreignid =\
            dictionary.get("foreignid")\
            if dictionary.get("foreignid")\
                else None
        lastupdated = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("lastupdated")).datetime\
            if dictionary.get("lastupdated") else None
        rulechain =\
            dictionary.get("rulechain")\
            if dictionary.get("rulechain")\
                else None
        versionid =\
            dictionary.get("versionid")\
            if dictionary.get("versionid")\
                else None
        accountclientid =\
            dictionary.get("accountclientid")\
            if dictionary.get("accountclientid")\
                else APIHelper.SKIP
        billingaccountid =\
            dictionary.get("billingaccountid")\
            if dictionary.get("billingaccountid")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        deviceid =\
            dictionary.get("deviceid")\
            if dictionary.get("deviceid")\
                else APIHelper.SKIP
        disabled =\
            dictionary.get("disabled")\
            if "disabled" in dictionary.keys()\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        rulesyntax =\
            dictionary.get("rulesyntax")\
            if dictionary.get("rulesyntax")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(createdon,
                   foreignid,
                   lastupdated,
                   rulechain,
                   versionid,
                   accountclientid,
                   billingaccountid,
                   description,
                   deviceid,
                   disabled,
                   id,
                   name,
                   rulesyntax,
                   version)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _accountclientid=(
            self.accountclientid
            if hasattr(self, "accountclientid")
            else None
        )
        _billingaccountid=(
            self.billingaccountid
            if hasattr(self, "billingaccountid")
            else None
        )
        _createdon=self.createdon
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _deviceid=(
            self.deviceid
            if hasattr(self, "deviceid")
            else None
        )
        _disabled=(
            self.disabled
            if hasattr(self, "disabled")
            else None
        )
        _foreignid=self.foreignid
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _lastupdated=self.lastupdated
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _rulechain=self.rulechain
        _rulesyntax=(
            self.rulesyntax
            if hasattr(self, "rulesyntax")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _versionid=self.versionid
        return (
            f"{self.__class__.__name__}("
            f"accountclientid={_accountclientid!r}, "
            f"billingaccountid={_billingaccountid!r}, "
            f"createdon={_createdon!r}, "
            f"description={_description!r}, "
            f"deviceid={_deviceid!r}, "
            f"disabled={_disabled!r}, "
            f"foreignid={_foreignid!r}, "
            f"id={_id!r}, "
            f"lastupdated={_lastupdated!r}, "
            f"name={_name!r}, "
            f"rulechain={_rulechain!r}, "
            f"rulesyntax={_rulesyntax!r}, "
            f"version={_version!r}, "
            f"versionid={_versionid!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _accountclientid=(
            self.accountclientid
            if hasattr(self, "accountclientid")
            else None
        )
        _billingaccountid=(
            self.billingaccountid
            if hasattr(self, "billingaccountid")
            else None
        )
        _createdon=self.createdon
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _deviceid=(
            self.deviceid
            if hasattr(self, "deviceid")
            else None
        )
        _disabled=(
            self.disabled
            if hasattr(self, "disabled")
            else None
        )
        _foreignid=self.foreignid
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _lastupdated=self.lastupdated
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _rulechain=self.rulechain
        _rulesyntax=(
            self.rulesyntax
            if hasattr(self, "rulesyntax")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _versionid=self.versionid
        return (
            f"{self.__class__.__name__}("
            f"accountclientid={_accountclientid!s}, "
            f"billingaccountid={_billingaccountid!s}, "
            f"createdon={_createdon!s}, "
            f"description={_description!s}, "
            f"deviceid={_deviceid!s}, "
            f"disabled={_disabled!s}, "
            f"foreignid={_foreignid!s}, "
            f"id={_id!s}, "
            f"lastupdated={_lastupdated!s}, "
            f"name={_name!s}, "
            f"rulechain={_rulechain!s}, "
            f"rulesyntax={_rulesyntax!s}, "
            f"version={_version!s}, "
            f"versionid={_versionid!s}, "
            f")"
        )
