"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.dto_fields import DtoFields


class ResourceEvent(object):
    """Implementation of the 'resource.Event' model.

    Attributes:
        accountclientid (str): Not used in this release, future functionality
        callbackurl (str): The URL of the callback listener
        createdon (datetime): Timestamp of the record
        description (str): a short description
        deviceid (str): This is a UUID value of the device created when the device is
            onboarded
        errmsg (str): Error message
        fieldid (str): The model property of type str.
        fields (DtoFields): Fields to return needed by search
        fieldvalue (List[int]): The model property of type List[int].
        foreignid (str): UUID of the ECPD account the user belongs to
        id (str): UUID of the user record, assigned at creation
        lastupdated (datetime): Timestamp of the record
        modelid (str): The model ID of the device
        name (str): User defined name of the record
        sensordataaggregation (bool): A flag to indicate if sensor data is to be
            aggregated (true) or not
        state (str): The current status of the device or transaction and will be
            `success` or `failed`
        transactionid (str): The system-generated UUID of the transaction
        version (str): The resource version
        versionid (str): The UUID of the resource version

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "createdon": "createdon",
        "fieldid": "fieldid",
        "foreignid": "foreignid",
        "lastupdated": "lastupdated",
        "state": "state",
        "versionid": "versionid",
        "accountclientid": "accountclientid",
        "callbackurl": "callbackurl",
        "description": "description",
        "deviceid": "deviceid",
        "errmsg": "errmsg",
        "fields": "fields",
        "fieldvalue": "fieldvalue",
        "id": "id",
        "modelid": "modelid",
        "name": "name",
        "sensordataaggregation": "sensordataaggregation",
        "transactionid": "transactionid",
        "version": "version",
    }

    _optionals = [
        "accountclientid",
        "callbackurl",
        "description",
        "deviceid",
        "errmsg",
        "fields",
        "fieldvalue",
        "id",
        "modelid",
        "name",
        "sensordataaggregation",
        "transactionid",
        "version",
    ]

    def __init__(
        self,
        createdon=None,
        fieldid=None,
        foreignid=None,
        lastupdated=None,
        state=None,
        versionid=None,
        accountclientid=APIHelper.SKIP,
        callbackurl=APIHelper.SKIP,
        description=APIHelper.SKIP,
        deviceid=APIHelper.SKIP,
        errmsg=APIHelper.SKIP,
        fields=APIHelper.SKIP,
        fieldvalue=APIHelper.SKIP,
        id=APIHelper.SKIP,
        modelid=APIHelper.SKIP,
        name=APIHelper.SKIP,
        sensordataaggregation=APIHelper.SKIP,
        transactionid=APIHelper.SKIP,
        version=APIHelper.SKIP):
        """Initialize a ResourceEvent instance."""
        # Initialize members of the class
        if accountclientid is not APIHelper.SKIP:
            self.accountclientid = accountclientid
        if callbackurl is not APIHelper.SKIP:
            self.callbackurl = callbackurl
        self.createdon =\
             APIHelper.apply_datetime_converter(
            createdon, APIHelper.RFC3339DateTime)\
             if createdon else None
        if description is not APIHelper.SKIP:
            self.description = description
        if deviceid is not APIHelper.SKIP:
            self.deviceid = deviceid
        if errmsg is not APIHelper.SKIP:
            self.errmsg = errmsg
        self.fieldid = fieldid
        if fields is not APIHelper.SKIP:
            self.fields = fields
        if fieldvalue is not APIHelper.SKIP:
            self.fieldvalue = fieldvalue
        self.foreignid = foreignid
        if id is not APIHelper.SKIP:
            self.id = id
        self.lastupdated =\
             APIHelper.apply_datetime_converter(
            lastupdated, APIHelper.RFC3339DateTime)\
             if lastupdated else None
        if modelid is not APIHelper.SKIP:
            self.modelid = modelid
        if name is not APIHelper.SKIP:
            self.name = name
        if sensordataaggregation is not APIHelper.SKIP:
            self.sensordataaggregation = sensordataaggregation
        self.state = state
        if transactionid is not APIHelper.SKIP:
            self.transactionid = transactionid
        if version is not APIHelper.SKIP:
            self.version = version
        self.versionid = versionid

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        createdon = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("createdon")).datetime\
            if dictionary.get("createdon") else None
        fieldid =\
            dictionary.get("fieldid")\
            if dictionary.get("fieldid")\
                else None
        foreignid =\
            dictionary.get("foreignid")\
            if dictionary.get("foreignid")\
                else None
        lastupdated = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("lastupdated")).datetime\
            if dictionary.get("lastupdated") else None
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else None
        versionid =\
            dictionary.get("versionid")\
            if dictionary.get("versionid")\
                else None
        accountclientid =\
            dictionary.get("accountclientid")\
            if dictionary.get("accountclientid")\
                else APIHelper.SKIP
        callbackurl =\
            dictionary.get("callbackurl")\
            if dictionary.get("callbackurl")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        deviceid =\
            dictionary.get("deviceid")\
            if dictionary.get("deviceid")\
                else APIHelper.SKIP
        errmsg =\
            dictionary.get("errmsg")\
            if dictionary.get("errmsg")\
                else APIHelper.SKIP
        fields =\
            DtoFields.from_dictionary(
                dictionary.get("fields"))\
                if "fields" in dictionary.keys()\
                else APIHelper.SKIP
        fieldvalue =\
            dictionary.get("fieldvalue")\
            if dictionary.get("fieldvalue")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        modelid =\
            dictionary.get("modelid")\
            if dictionary.get("modelid")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        sensordataaggregation =\
            dictionary.get("sensordataaggregation")\
            if "sensordataaggregation" in dictionary.keys()\
                else APIHelper.SKIP
        transactionid =\
            dictionary.get("transactionid")\
            if dictionary.get("transactionid")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(createdon,
                   fieldid,
                   foreignid,
                   lastupdated,
                   state,
                   versionid,
                   accountclientid,
                   callbackurl,
                   description,
                   deviceid,
                   errmsg,
                   fields,
                   fieldvalue,
                   id,
                   modelid,
                   name,
                   sensordataaggregation,
                   transactionid,
                   version)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _accountclientid=(
            self.accountclientid
            if hasattr(self, "accountclientid")
            else None
        )
        _callbackurl=(
            self.callbackurl
            if hasattr(self, "callbackurl")
            else None
        )
        _createdon=self.createdon
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _deviceid=(
            self.deviceid
            if hasattr(self, "deviceid")
            else None
        )
        _errmsg=(
            self.errmsg
            if hasattr(self, "errmsg")
            else None
        )
        _fieldid=self.fieldid
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _fieldvalue=(
            self.fieldvalue
            if hasattr(self, "fieldvalue")
            else None
        )
        _foreignid=self.foreignid
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _lastupdated=self.lastupdated
        _modelid=(
            self.modelid
            if hasattr(self, "modelid")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _sensordataaggregation=(
            self.sensordataaggregation
            if hasattr(self, "sensordataaggregation")
            else None
        )
        _state=self.state
        _transactionid=(
            self.transactionid
            if hasattr(self, "transactionid")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _versionid=self.versionid
        return (
            f"{self.__class__.__name__}("
            f"accountclientid={_accountclientid!r}, "
            f"callbackurl={_callbackurl!r}, "
            f"createdon={_createdon!r}, "
            f"description={_description!r}, "
            f"deviceid={_deviceid!r}, "
            f"errmsg={_errmsg!r}, "
            f"fieldid={_fieldid!r}, "
            f"fields={_fields!r}, "
            f"fieldvalue={_fieldvalue!r}, "
            f"foreignid={_foreignid!r}, "
            f"id={_id!r}, "
            f"lastupdated={_lastupdated!r}, "
            f"modelid={_modelid!r}, "
            f"name={_name!r}, "
            f"sensordataaggregation={_sensordataaggregation!r}, "
            f"state={_state!r}, "
            f"transactionid={_transactionid!r}, "
            f"version={_version!r}, "
            f"versionid={_versionid!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _accountclientid=(
            self.accountclientid
            if hasattr(self, "accountclientid")
            else None
        )
        _callbackurl=(
            self.callbackurl
            if hasattr(self, "callbackurl")
            else None
        )
        _createdon=self.createdon
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _deviceid=(
            self.deviceid
            if hasattr(self, "deviceid")
            else None
        )
        _errmsg=(
            self.errmsg
            if hasattr(self, "errmsg")
            else None
        )
        _fieldid=self.fieldid
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _fieldvalue=(
            self.fieldvalue
            if hasattr(self, "fieldvalue")
            else None
        )
        _foreignid=self.foreignid
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _lastupdated=self.lastupdated
        _modelid=(
            self.modelid
            if hasattr(self, "modelid")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _sensordataaggregation=(
            self.sensordataaggregation
            if hasattr(self, "sensordataaggregation")
            else None
        )
        _state=self.state
        _transactionid=(
            self.transactionid
            if hasattr(self, "transactionid")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _versionid=self.versionid
        return (
            f"{self.__class__.__name__}("
            f"accountclientid={_accountclientid!s}, "
            f"callbackurl={_callbackurl!s}, "
            f"createdon={_createdon!s}, "
            f"description={_description!s}, "
            f"deviceid={_deviceid!s}, "
            f"errmsg={_errmsg!s}, "
            f"fieldid={_fieldid!s}, "
            f"fields={_fields!s}, "
            f"fieldvalue={_fieldvalue!s}, "
            f"foreignid={_foreignid!s}, "
            f"id={_id!s}, "
            f"lastupdated={_lastupdated!s}, "
            f"modelid={_modelid!s}, "
            f"name={_name!s}, "
            f"sensordataaggregation={_sensordataaggregation!s}, "
            f"state={_state!s}, "
            f"transactionid={_transactionid!s}, "
            f"version={_version!s}, "
            f"versionid={_versionid!s}, "
            f")"
        )
