"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class RoadworksCauseCode(object):
    """Implementation of the 'RoadworksCauseCode' model.

    Cause code wrapper for roadworks events.

    Attributes:
        roadworks_3 (int): The value shall be set to: - 0 `unavailable`
            - in case further detailed information on roadworks is unavailable, - 1
            `majorRoadworks`              - in case a major roadworks is ongoing, - 2
            `roadMarkingWork`             - in case a road marking work is ongoing, -
            3 `slowMovingRoadMaintenance`   - in case slow moving road maintenance
            work is ongoing, - 4 `shortTermStationaryRoadworks`- in case a short term
            stationary roadwork is ongoing, - 5 `streetCleaning`              - in
            case a vehicle street cleaning work is ongoing, - 6 `winterService`
            - in case winter service work is ongoing, - 7 `setupPhase`
            - in case the work zone is being setup, - 8 `remodellingPhase`
            - in case the work zone is being changed, - 9 `dismantlingPhase`
            - in case the work zone is being dismantled after finished work. - 10-255
            - are reserved for future usage.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "roadworks_3": "roadworks3",
    }

    def __init__(
        self,
        roadworks_3=None):
        """Initialize a RoadworksCauseCode instance."""
        # Initialize members of the class
        self.roadworks_3 = roadworks_3

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        roadworks_3 =\
            dictionary.get("roadworks3")\
            if dictionary.get("roadworks3")\
                else None

        # Return an object of this model
        return cls(roadworks_3)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.roadworks_3,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("roadworks3"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _roadworks_3=self.roadworks_3
        return (
            f"{self.__class__.__name__}("
            f"roadworks_3={_roadworks_3!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _roadworks_3=self.roadworks_3
        return (
            f"{self.__class__.__name__}("
            f"roadworks_3={_roadworks_3!s}, "
            f")"
        )
