"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.models.sae_alert_payload import (
    SaeAlertPayload,
)


class SaeAlertMessage(object):
    """Implementation of the 'SaeAlertMessage' model.

    Road Side Alert (RSA) message and its mandatory fields. This message is used to
    send alerts for nearby hazards to travelers. This message is defined in the SAE
    J2735 Standard. The system supports all mandatory fields, but only a subset of
    the optional fields.

    Attributes:
        sae_alert (SaeAlertPayload): Road Side Alert (RSA) message payload as defined
            in SAE J2735.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "sae_alert": "saeAlert",
    }

    def __init__(
        self,
        sae_alert=None):
        """Initialize a SaeAlertMessage instance."""
        # Initialize members of the class
        self.sae_alert = sae_alert

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        sae_alert =\
            SaeAlertPayload.from_dictionary(
                dictionary.get("saeAlert"))\
                if dictionary.get("saeAlert") else None

        # Return an object of this model
        return cls(sae_alert)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _sae_alert=self.sae_alert
        return (
            f"{self.__class__.__name__}("
            f"sae_alert={_sae_alert!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _sae_alert=self.sae_alert
        return (
            f"{self.__class__.__name__}("
            f"sae_alert={_sae_alert!s}, "
            f")"
        )
