"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.models.dto_off_board_sensor import (
    DtoOffBoardSensor,
)


class Sensorinsightsconfig(object):
    """Implementation of the 'sensorinsightsconfig' model.

    The configuration of the remove request

    Attributes:
        removesensor (DtoOffBoardSensor): The EUI64 address of the device being
            removed

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "removesensor": "removesensor",
    }

    _optionals = [
        "removesensor",
    ]

    def __init__(
        self,
        removesensor=APIHelper.SKIP):
        """Initialize a Sensorinsightsconfig instance."""
        # Initialize members of the class
        if removesensor is not APIHelper.SKIP:
            self.removesensor = removesensor

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        removesensor =\
            DtoOffBoardSensor.from_dictionary(
                dictionary.get("removesensor"))\
                if "removesensor" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(removesensor)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _removesensor=(
            self.removesensor
            if hasattr(self, "removesensor")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"removesensor={_removesensor!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _removesensor=(
            self.removesensor
            if hasattr(self, "removesensor")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"removesensor={_removesensor!s}, "
            f")"
        )
