"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class SmsMessagesResponse(object):
    """Implementation of the 'SmsMessagesResponse' model.

    Attributes:
        messages (List[GIOSmsMessage] | None): The model property of type
            List[GIOSmsMessage] | None.
        has_more_data (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "messages": "messages",
        "has_more_data": "hasMoreData",
    }

    _optionals = [
        "messages",
        "has_more_data",
    ]

    def __init__(
        self,
        messages=APIHelper.SKIP,
        has_more_data=APIHelper.SKIP):
        """Initialize a SmsMessagesResponse instance."""
        # Initialize members of the class
        if messages is not APIHelper.SKIP:
            self.messages = messages
        if has_more_data is not APIHelper.SKIP:
            self.has_more_data = has_more_data

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        messages = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("SmsMessagesResponseMessages"),
            dictionary.get("messages"),
            False)\
            if dictionary.get("messages") is not None\
            else APIHelper.SKIP
        has_more_data =\
            dictionary.get("hasMoreData")\
            if "hasMoreData" in dictionary.keys()\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(messages,
                   has_more_data)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _messages=(
            self.messages
            if hasattr(self, "messages")
            else None
        )
        _has_more_data=(
            self.has_more_data
            if hasattr(self, "has_more_data")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"messages={_messages!r}, "
            f"has_more_data={_has_more_data!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _messages=(
            self.messages
            if hasattr(self, "messages")
            else None
        )
        _has_more_data=(
            self.has_more_data
            if hasattr(self, "has_more_data")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"messages={_messages!s}, "
            f"has_more_data={_has_more_data!s}, "
            f")"
        )
