"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class SpeedLimitContent(object):
    """Implementation of the 'SpeedLimitContent' model.

    DataFrame content variant carrying speed limit information.

    Attributes:
        speed_limit (List[ITISItemWrapper | TextPhraseItemWrapper]): List of speed
            limits and cautions.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "speed_limit": "speedLimit",
    }

    def __init__(
        self,
        speed_limit=None):
        """Initialize a SpeedLimitContent instance."""
        # Initialize members of the class
        self.speed_limit = speed_limit

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        speed_limit = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("TextPhraseOrITIS"),
            dictionary.get("speedLimit"),
            False)\
            if dictionary.get("speedLimit") is not None\
            else None

        # Return an object of this model
        return cls(speed_limit)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return (UnionTypeLookUp.get("TextPhraseOrITIS")
                .validate(dictionary.speed_limit).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return (UnionTypeLookUp.get("TextPhraseOrITIS")
            .validate(dictionary.get("speedLimit")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _speed_limit=self.speed_limit
        return (
            f"{self.__class__.__name__}("
            f"speed_limit={_speed_limit!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _speed_limit=self.speed_limit
        return (
            f"{self.__class__.__name__}("
            f"speed_limit={_speed_limit!s}, "
            f")"
        )
