"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TriggerConditionEnum(object):
    """Implementation of the 'TriggerCondition' enum.

    The following options are supported as Trigger TriggerConditions:
      - enter: The message is triggered when the road user enters the geofence. For
    polygons and multi-polygons only. In case of multi-polygons the message is
    triggered when the road user enters any of the polygons.
      - leave: The message is triggered when the road user leaves the geofence. For
    polygons and multi-polygons only. In case of multi-polygons the message is
    triggered when the road user leaves any of the polygons.
      - inside: The message is triggered when the road user is inside the geofence.
    For polygons and multi-polygons only. In case of multi-polygons the message is
    triggered when the road user is inside any of the polygons.
      - crossing: The message is triggered when the road user crosses the geofence.
    For lines and multi-lines only. In case of multi-lines the message is triggered
    when the road user crosses any of the lines.

    Attributes:
        ENTER: The enum member of type str.
        LEAVE: The enum member of type str.
        INSIDE: The enum member of type str.
        CROSSING: The enum member of type str.

    """

    _all_values = ["enter", "leave", "inside", "crossing"]
    ENTER = "enter"

    LEAVE = "leave"

    INSIDE = "inside"

    CROSSING = "crossing"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
