"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class TriggerValueResponse(object):
    """Implementation of the 'TriggerValueResponse' model.

    Attributes:
        triggers (List[Triggervalues] | None): The model property of type
            List[Triggervalues] | None.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "triggers": "triggers",
    }

    _optionals = [
        "triggers",
    ]

    def __init__(
        self,
        triggers=APIHelper.SKIP):
        """Initialize a TriggerValueResponse instance."""
        # Initialize members of the class
        if triggers is not APIHelper.SKIP:
            self.triggers = triggers

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        triggers = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("TriggervalueChunk"),
            dictionary.get("triggers"),
            False)\
            if dictionary.get("triggers") is not None\
            else APIHelper.SKIP

        # Return an object of this model
        return cls(triggers)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _triggers=(
            self.triggers
            if hasattr(self, "triggers")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"triggers={_triggers!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _triggers=(
            self.triggers
            if hasattr(self, "triggers")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"triggers={_triggers!s}, "
            f")"
        )
