"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class UsageTriggerAddRequest(object):
    """Implementation of the 'UsageTriggerAddRequest' model.

    Attributes:
        trigger_name (str): Usage trigger name
        account_name (str): Account name
        service_name (ServiceNameEnum): Service name
        threshold_value (str): The percent of subscribed usage required to activate
            the trigger, such as 90 or 100.
        allow_excess (bool): Allow additional requests after thresholdValue is
            reached. (currently not functional)
        send_sms_notification (bool): Send SMS (text) alerts when the thresholdValue
            is reached.
        sms_phone_numbers (str): Comma-separated list of phone numbers to send SMS
            alerts to. Digits only; no dashes or parentheses, etc.
        send_email_notification (bool): Send email alerts when the thresholdValue is
            reached.
        email_addresses (str): Comma-separated list of email addresses to send alerts
            to.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_name": "accountName",
        "service_name": "serviceName",
        "threshold_value": "thresholdValue",
        "trigger_name": "triggerName",
        "allow_excess": "allowExcess",
        "send_sms_notification": "sendSmsNotification",
        "sms_phone_numbers": "smsPhoneNumbers",
        "send_email_notification": "sendEmailNotification",
        "email_addresses": "emailAddresses",
    }

    _optionals = [
        "trigger_name",
        "allow_excess",
        "send_sms_notification",
        "sms_phone_numbers",
        "send_email_notification",
        "email_addresses",
    ]

    def __init__(
        self,
        account_name=None,
        service_name="Location",
        threshold_value=None,
        trigger_name=APIHelper.SKIP,
        allow_excess=APIHelper.SKIP,
        send_sms_notification=APIHelper.SKIP,
        sms_phone_numbers=APIHelper.SKIP,
        send_email_notification=APIHelper.SKIP,
        email_addresses=APIHelper.SKIP):
        """Initialize a UsageTriggerAddRequest instance."""
        # Initialize members of the class
        if trigger_name is not APIHelper.SKIP:
            self.trigger_name = trigger_name
        self.account_name = account_name
        self.service_name = service_name
        self.threshold_value = threshold_value
        if allow_excess is not APIHelper.SKIP:
            self.allow_excess = allow_excess
        if send_sms_notification is not APIHelper.SKIP:
            self.send_sms_notification = send_sms_notification
        if sms_phone_numbers is not APIHelper.SKIP:
            self.sms_phone_numbers = sms_phone_numbers
        if send_email_notification is not APIHelper.SKIP:
            self.send_email_notification = send_email_notification
        if email_addresses is not APIHelper.SKIP:
            self.email_addresses = email_addresses

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_name =\
            dictionary.get("accountName")\
            if dictionary.get("accountName")\
                else None
        service_name =\
            dictionary.get("serviceName")\
            if dictionary.get("serviceName")\
                else "Location"
        threshold_value =\
            dictionary.get("thresholdValue")\
            if dictionary.get("thresholdValue")\
                else None
        trigger_name =\
            dictionary.get("triggerName")\
            if dictionary.get("triggerName")\
                else APIHelper.SKIP
        allow_excess =\
            dictionary.get("allowExcess")\
            if "allowExcess" in dictionary.keys()\
                else APIHelper.SKIP
        send_sms_notification =\
            dictionary.get("sendSmsNotification")\
            if "sendSmsNotification" in dictionary.keys()\
                else APIHelper.SKIP
        sms_phone_numbers =\
            dictionary.get("smsPhoneNumbers")\
            if dictionary.get("smsPhoneNumbers")\
                else APIHelper.SKIP
        send_email_notification =\
            dictionary.get("sendEmailNotification")\
            if "sendEmailNotification" in dictionary.keys()\
                else APIHelper.SKIP
        email_addresses =\
            dictionary.get("emailAddresses")\
            if dictionary.get("emailAddresses")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(account_name,
                   service_name,
                   threshold_value,
                   trigger_name,
                   allow_excess,
                   send_sms_notification,
                   sms_phone_numbers,
                   send_email_notification,
                   email_addresses)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _trigger_name=(
            self.trigger_name
            if hasattr(self, "trigger_name")
            else None
        )
        _account_name=self.account_name
        _service_name=self.service_name
        _threshold_value=self.threshold_value
        _allow_excess=(
            self.allow_excess
            if hasattr(self, "allow_excess")
            else None
        )
        _send_sms_notification=(
            self.send_sms_notification
            if hasattr(self, "send_sms_notification")
            else None
        )
        _sms_phone_numbers=(
            self.sms_phone_numbers
            if hasattr(self, "sms_phone_numbers")
            else None
        )
        _send_email_notification=(
            self.send_email_notification
            if hasattr(self, "send_email_notification")
            else None
        )
        _email_addresses=(
            self.email_addresses
            if hasattr(self, "email_addresses")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"trigger_name={_trigger_name!r}, "
            f"account_name={_account_name!r}, "
            f"service_name={_service_name!r}, "
            f"threshold_value={_threshold_value!r}, "
            f"allow_excess={_allow_excess!r}, "
            f"send_sms_notification={_send_sms_notification!r}, "
            f"sms_phone_numbers={_sms_phone_numbers!r}, "
            f"send_email_notification={_send_email_notification!r}, "
            f"email_addresses={_email_addresses!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _trigger_name=(
            self.trigger_name
            if hasattr(self, "trigger_name")
            else None
        )
        _account_name=self.account_name
        _service_name=self.service_name
        _threshold_value=self.threshold_value
        _allow_excess=(
            self.allow_excess
            if hasattr(self, "allow_excess")
            else None
        )
        _send_sms_notification=(
            self.send_sms_notification
            if hasattr(self, "send_sms_notification")
            else None
        )
        _sms_phone_numbers=(
            self.sms_phone_numbers
            if hasattr(self, "sms_phone_numbers")
            else None
        )
        _send_email_notification=(
            self.send_email_notification
            if hasattr(self, "send_email_notification")
            else None
        )
        _email_addresses=(
            self.email_addresses
            if hasattr(self, "email_addresses")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"trigger_name={_trigger_name!s}, "
            f"account_name={_account_name!s}, "
            f"service_name={_service_name!s}, "
            f"threshold_value={_threshold_value!s}, "
            f"allow_excess={_allow_excess!s}, "
            f"send_sms_notification={_send_sms_notification!s}, "
            f"sms_phone_numbers={_sms_phone_numbers!s}, "
            f"send_email_notification={_send_email_notification!s}, "
            f"email_addresses={_email_addresses!s}, "
            f")"
        )
