"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper


class WorkZoneContent(object):
    """Implementation of the 'WorkZoneContent' model.

    DataFrame content variant carrying work zone information.

    Attributes:
        work_zone (List[ITISItemWrapper | TextPhraseItemWrapper]): List of work zone
            signs and directions.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "work_zone": "workZone",
    }

    def __init__(
        self,
        work_zone=None):
        """Initialize a WorkZoneContent instance."""
        # Initialize members of the class
        self.work_zone = work_zone

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        work_zone = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("TextPhraseOrITIS"),
            dictionary.get("workZone"),
            False)\
            if dictionary.get("workZone") is not None\
            else None

        # Return an object of this model
        return cls(work_zone)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from verizon.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return (UnionTypeLookUp.get("TextPhraseOrITIS")
                .validate(dictionary.work_zone).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return (UnionTypeLookUp.get("TextPhraseOrITIS")
            .validate(dictionary.get("workZone")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _work_zone=self.work_zone
        return (
            f"{self.__class__.__name__}("
            f"work_zone={_work_zone!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _work_zone=self.work_zone
        return (
            f"{self.__class__.__name__}("
            f"work_zone={_work_zone!s}, "
            f")"
        )
