"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from verizon.api_helper import APIHelper
from verizon.exceptions.api_exception import (
    APIException,
)


class M500ManagementErrorException(APIException):
    def __init__(self, reason, response):
        """Initialize M500ManagementErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(M500ManagementErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.error =\
            dictionary.get("error")\
            if dictionary.get("error")\
                else None
        self.error_description =\
            dictionary.get("error_description")\
            if dictionary.get("error_description")\
                else None
        self.cause =\
            dictionary.get("cause")\
            if dictionary.get("cause")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _error=(
            self.error
            if hasattr(self, "error")
            else None
        )
        _error_description=(
            self.error_description
            if hasattr(self, "error_description")
            else None
        )
        _cause=(
            self.cause
            if hasattr(self, "cause")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"error={_error!s}, "
            f"error_description={_error_description!s}, "
            f"cause={_cause!s}, "
            f")"
        )
